# Literature Scanning: Step 2 - Extracting data from papers with LLMs

In [1]:
import pandas as pd
from discovery_utils.utils.llm import batch_check

import pandas as pd
import os

# Alternative: s3://discovery-iss/data/afs_scanning/afs_open_alex_scan_parenting_interventions.csv
INPUT_DATA = 'afs_open_alex_scan_parenting_interventions.csv'

data_df = (
    pd.read_csv(INPUT_DATA)
    .query("publication_year >= 2000")
    .assign(text = lambda df: df['title'] + ' ' + df['abstract'])
)
len(data_df)

# testing on a smaller sample for now
# data_df = data_df.sample(100, random_state=42)

34145

In [2]:
from ast import literal_eval

def extract_author_countries(authorships):
    try:
        # Convert the string representation of the list to an actual list
        authors = literal_eval(authorships)
        countries = []
        for author in authors:
            for institution in author.get('institutions', []):
                if 'country_code' in institution:
                    countries.append(institution['country_code'])
        # remove null values
        countries = [country for country in countries if country is not None]
        return sorted(list(set(countries)))
    except (ValueError, SyntaxError):
        # Handle the case where the string cannot be evaluated
        return []

## Run the LLM pipeline

In [ ]:
_data_df = data_df
ids = _data_df.id.tolist()
text = data_df.text.tolist()
test_data = dict(zip(ids, text))

In [5]:
len(test_data)

34145

In [22]:
system_message = """
    Extract structured information about a parenting programme from the provided text.
    We are looking for programmes that are evidence-based (i.e. rigorously evaluated) and targeted at parents from pregnancy up to when their
    child is 5 years old.

    The programme could be relevant to developmental, behavioural, or well-being outcomes
    such as children language development, cognitive development, social-emotional skills, physical and mental health, or
    parental outcomes such as confidence, skills, behaviours, knowledge, self-efficacy, and well-being.
    
    Unless requested otherwise, adhere as precisely as possible to the language and text that is used in the provided text document.
    
    If the requested information is not described, return N/A. DO NOT make up any false information or false inferences.
"""

fields = [
    # Relevance
    {"name": "is_relevant", "type": "str", "description": "One-word answer: 'yes' if the text is about a parenting programme targeted at parents at any stage from pregnancy up to when the child is 5 years old, otherwise 'no'."},
    {"name": "is_relevant_reason", "type": "str", "description": "Short explanation (one sentence, 20 words) of why the text is relevant or not."},
    # Details about the programme
    {"name": "programme_name", "type": "str", "description": "The name of the programme or intervention."},
    {"name": "summary", "type": "str", "description": "A brief summary of what the programme involves and what it aims to achieve."},
    
    {"name": "child_outcomes_targeted", "type": "list[str]", "description": "Child-related outcomes the programme seeks to improve (e.g., 'language', 'cognitive development', 'social-emotional skills')."},
    {"name": "child_outcomes_category", "type": "list[str]", "description": "Infer if the child-related outcomes are best categorised in one of the following: 'Physical health and development', 'Mental health', 'Social, emotional and behavioral', 'Cognitive development', 'Speech, language and communication', 'N/A'."},
    {"name": "parent_outcomes_targeted", "type": "list[str]", "description": "Parent-related outcomes the programme targets (e.g., 'confidence', 'knowledge', 'wellbeing', 'skills')."},
    {"name": "parent_outcomes_category", "type": "list[str]", "description": "Infer if the parent-related outcomes are best categorised in one of the following: 'Parental behaviours and skills', 'Parental beliefs and knowledge', 'Parental well-being and mental health', 'N/A'."},    

    # Digital
    {"name": "digital_component", "type": "str", "description": "One-word answer: 'yes' if programme includes a digital component (e.g., text messages, online modules), otherwise 'no'."},
    {"name": "digital_component_description", "type": "str", "description": "Brief description of the digital component, if any."},
    
    # Context
    {"name": "country", "type": "str", "description": "The country or countries where the programme was delivered."},

    {"name": "age_range", "type": "str", "description": "The programme is aimed at parents of what age group? E.g., 'pregnancy','0-5 years', 'infants', 'toddlers'."},
    {"name": "age_range_numerical", "type": "str", "description": "Infer the probable age range in years and in numerical format (e.g., '0-5', '0-2', '3-5'). This should be '-1' if the programme is aimed at pregnancy."},

    {"name": "target_population", "type": "str", "description": "Description of the parent population the programme is aimed at (e.g., low-income mothers, ethnic minorities, parents under 25)."},    
    {"name": "disadvantaged_groups_engaged", "type": "list[str]", "description": "List of any specific disadvantaged groups the programme has successfully engaged, if described. Otherwise return N/A"},

    # Engagement details
    {"name": "is_about_engagement", "type": "str", "description": "One-word answer: 'yes' if the text is specifically about evaluating a strategy for engaging or recruiting families into interventions, otherwise 'no'."},

    {"name": "engagement_strategies", "type": "list[str]", "description": "Recruitment and engagement strategies used, if described."},
    {"name": "engagement_success", "type": "str", "description": "Any information about how successful the engagement strategies were."},
    {"name": "barriers_to_engagement", "type": "list[str]", "description": "Barriers or challenges mentioned regarding recruitment or engagement."},
    {"name": "other_engagement_learnings", "type": "list[str]", "description": "Other useful insights about recruitment, or engagement, if any."},
    
    # More details about the study
    {"name": "study_type", "type": "str", "description": "If possible, identify the type of study. Provide only the letter a-i: (a) Purely cross-sectional study without control variables, (b) Study measures outcome pre and post without control variables, (c) Purely cross-section study, uses control variables, (d) Study measures outcomes pre and post, uses control variables or matching tecniques, (e) Comparison of outcomes in treated group and comparison group, with counterfactuals (f) Quasi-experimental study, (g) Randomised controlled trial, (h) Meta-analysis, (i) N/A."},
    {"name": "programme_evaluation_desc", "type": "str", "description": "Description of how the programme was evaluated."},
    {"name": "evidence_of_effectiveness", "type": "list[str]", "description": "Evidence of outcomes, effectiveness, or evaluations cited."},
    {"name": "limitations", "type": "list[str]", "description": "Any limitations of the programme or study mentioned."},
]

In [ ]:
processor = batch_check.LLMProcessor(
    model_name="gpt-4.1-mini",
    # model_name="gpt-4o-mini",
    temperature=0,
    output_path="afs_open_alex_scan_2.jsonl",
    system_message=system_message,
    session_name="afs_open_alex_scan",
    output_fields=fields,
)

processor.run(test_data, batch_size=30, sleep_time=0.5)

2025-05-16 17:10:23,044 - root - INFO - Using OpenAI

2025-05-16 17:10:23,209 - root - INFO - Processing batch 1/1130
2025-05-16 17:10:33,929 - root - INFO - Processing batch 2/1130
2025-05-16 17:10:42,435 - root - INFO - Processing batch 3/1130
2025-05-16 17:10:53,297 - root - INFO - Processing batch 4/1130
2025-05-16 17:11:04,708 - root - INFO - Processing batch 5/1130
2025-05-16 17:11:19,128 - root - INFO - Processing batch 6/1130
2025-05-16 17:11:27,379 - root - INFO - Processing batch 7/1130
2025-05-16 17:11:37,641 - root - INFO - Processing batch 8/1130
2025-05-16 17:11:49,584 - root - INFO - Processing batch 9/1130
2025-05-16 17:12:02,225 - root - INFO - Processing batch 10/1130
2025-05-16 17:12:11,271 - root - INFO - Processing batch 11/1130
2025-05-16 17:12:18,857 - root - INFO - Processing batch 12/1130
2025-05-16 17:12:31,323 - root - INFO - Processing batch 13/1130
2025-05-16 17:12:43,336 - root - INFO - Processing batch 14/1130
2025-05-16 17:12:52,509 - root - INFO - Processing batch 15/1130
2025-05-16 17:13:01,154 - root - INFO - Processing batch 16/1130
2025-05-16 17:13:08,930 - root - INFO - Processing batch 17/1130
2025-05-16 17:13:20,399 - root - INFO - Processing batch 18/1130
2025-05-16 17:13:28,839 - root - INFO - Processing batch 19/1130
2025-05-16 17:13:40,129 - root - INFO - Processing batch 20/1130
2025-05-16 17:13:53,521 - root - INFO - Processing batch 21/1130
2025-05-16 17:14:01,849 - root - INFO - Processing batch 22/1130
2025-05-16 17:14:09,485 - root - INFO - Processing batch 23/1130
2025-05-16 17:14:19,434 - root - INFO - Processing batch 24/1130
2025-05-16 17:14:27,580 - root - INFO - Processing batch 25/1130
2025-05-16 17:14:39,659 - root - INFO - Processing batch 26/1130
2025-05-16 17:14:48,096 - root - INFO - Processing batch 27/1130
2025-05-16 17:14:55,304 - root - INFO - Processing batch 28/1130
2025-05-16 17:15:10,833 - root - INFO - Processing batch 29/1130
2025-05-16 17:15:21,488 - root - INFO - Processing batch 30/1130
2025-05-16 17:15:30,938 - root - INFO - Processing batch 31/1130
2025-05-16 17:15:41,047 - root - INFO - Processing batch 32/1130
2025-05-16 17:15:49,359 - root - INFO - Processing batch 33/1130
2025-05-16 17:15:58,526 - root - INFO - Processing batch 34/1130
2025-05-16 17:16:35,653 - root - INFO - Processing batch 35/1130
2025-05-16 17:16:44,346 - root - INFO - Processing batch 36/1130
2025-05-16 17:16:51,902 - root - INFO - Processing batch 37/1130
2025-05-16 17:17:00,220 - root - INFO - Processing batch 38/1130
2025-05-16 17:17:11,051 - root - INFO - Processing batch 39/1130
2025-05-16 17:17:20,402 - root - INFO - Processing batch 40/1130
2025-05-16 17:17:44,486 - root - INFO - Processing batch 41/1130
2025-05-16 17:18:18,954 - root - INFO - Processing batch 42/1130
2025-05-16 17:18:28,606 - root - INFO - Processing batch 43/1130
2025-05-16 17:18:37,323 - root - INFO - Processing batch 44/1130
2025-05-16 17:18:47,457 - root - INFO - Processing batch 45/1130
2025-05-16 17:18:55,324 - root - INFO - Processing batch 46/1130
2025-05-16 17:19:02,872 - root - INFO - Processing batch 47/1130
2025-05-16 17:19:12,580 - root - INFO - Processing batch 48/1130
2025-05-16 17:19:20,144 - root - INFO - Processing batch 49/1130
2025-05-16 17:19:28,057 - root - INFO - Processing batch 50/1130
2025-05-16 17:19:36,657 - root - INFO - Processing batch 51/1130
2025-05-16 17:20:11,716 - root - INFO - Processing batch 52/1130
2025-05-16 17:20:19,963 - root - INFO - Processing batch 53/1130
2025-05-16 17:20:29,367 - root - INFO - Processing batch 54/1130
2025-05-16 17:20:39,307 - root - INFO - Processing batch 55/1130
2025-05-16 17:21:08,523 - root - INFO - Processing batch 56/1130
2025-05-16 17:21:18,196 - root - INFO - Processing batch 57/1130
2025-05-16 17:21:26,003 - root - INFO - Processing batch 58/1130
2025-05-16 17:21:33,931 - root - INFO - Processing batch 59/1130
2025-05-16 17:21:43,233 - root - INFO - Processing batch 60/1130
2025-05-16 17:21:51,992 - root - INFO - Processing batch 61/1130
2025-05-16 17:22:01,592 - root - INFO - Processing batch 62/1130
2025-05-16 17:22:16,234 - root - INFO - Processing batch 63/1130
2025-05-16 17:22:28,912 - root - INFO - Processing batch 64/1130
2025-05-16 17:22:37,027 - root - INFO - Processing batch 65/1130
2025-05-16 17:22:49,124 - root - INFO - Processing batch 66/1130
2025-05-16 17:22:56,693 - root - INFO - Processing batch 67/1130
2025-05-16 17:23:05,482 - root - INFO - Processing batch 68/1130
2025-05-16 17:23:15,310 - root - INFO - Processing batch 69/1130
2025-05-16 17:23:26,767 - root - INFO - Processing batch 70/1130
2025-05-16 17:23:33,935 - root - INFO - Processing batch 71/1130
2025-05-16 17:24:43,853 - root - INFO - Processing batch 72/1130
2025-05-16 17:24:59,943 - root - INFO - Processing batch 73/1130
2025-05-16 17:25:07,539 - root - INFO - Processing batch 74/1130
2025-05-16 17:25:16,591 - root - INFO - Processing batch 75/1130
2025-05-16 17:25:26,743 - root - INFO - Processing batch 76/1130
2025-05-16 17:25:36,124 - root - INFO - Processing batch 77/1130
2025-05-16 17:25:47,374 - root - INFO - Processing batch 78/1130
2025-05-16 17:25:57,858 - root - INFO - Processing batch 79/1130
2025-05-16 17:26:18,871 - root - INFO - Processing batch 80/1130
2025-05-16 17:26:27,514 - root - INFO - Processing batch 81/1130
2025-05-16 17:26:38,924 - root - INFO - Processing batch 82/1130
2025-05-16 17:26:47,425 - root - INFO - Processing batch 83/1130
2025-05-16 17:27:01,029 - root - INFO - Processing batch 84/1130
2025-05-16 17:27:10,329 - root - INFO - Processing batch 85/1130
2025-05-16 17:27:18,404 - root - INFO - Processing batch 86/1130
2025-05-16 17:27:27,177 - root - INFO - Processing batch 87/1130
2025-05-16 17:27:36,515 - root - INFO - Processing batch 88/1130
2025-05-16 17:27:45,938 - root - INFO - Processing batch 89/1130
2025-05-16 17:27:54,598 - root - INFO - Processing batch 90/1130
2025-05-16 17:28:07,392 - root - INFO - Processing batch 91/1130
2025-05-16 17:28:17,922 - root - INFO - Processing batch 92/1130
2025-05-16 17:28:28,008 - root - INFO - Processing batch 93/1130
2025-05-16 17:28:38,447 - root - INFO - Processing batch 94/1130
2025-05-16 17:28:48,955 - root - INFO - Processing batch 95/1130
2025-05-16 17:29:02,053 - root - INFO - Processing batch 96/1130
2025-05-16 17:29:16,464 - root - INFO - Processing batch 97/1130
2025-05-16 17:29:28,947 - root - INFO - Processing batch 98/1130
2025-05-16 17:29:42,913 - root - INFO - Processing batch 99/1130
2025-05-16 17:29:51,942 - root - INFO - Processing batch 100/1130
2025-05-16 17:30:01,999 - root - INFO - Processing batch 101/1130
2025-05-16 17:30:11,195 - root - INFO - Processing batch 102/1130
2025-05-16 17:30:21,819 - root - INFO - Processing batch 103/1130
2025-05-16 17:30:35,993 - root - INFO - Processing batch 104/1130
2025-05-16 17:30:48,198 - root - INFO - Processing batch 105/1130
2025-05-16 17:30:58,262 - root - INFO - Processing batch 106/1130
2025-05-16 17:31:15,458 - root - INFO - Processing batch 107/1130
2025-05-16 17:31:27,382 - root - INFO - Processing batch 108/1130
2025-05-16 17:31:38,079 - root - INFO - Processing batch 109/1130
2025-05-16 17:31:45,226 - root - INFO - Processing batch 110/1130
2025-05-16 17:31:57,807 - root - INFO - Processing batch 111/1130
2025-05-16 17:32:10,819 - root - INFO - Processing batch 112/1130
2025-05-16 17:32:23,296 - root - INFO - Processing batch 113/1130
2025-05-16 17:32:33,038 - root - INFO - Processing batch 114/1130
2025-05-16 17:32:42,258 - root - INFO - Processing batch 115/1130
2025-05-16 17:32:53,766 - root - INFO - Processing batch 116/1130
2025-05-16 17:33:04,241 - root - INFO - Processing batch 117/1130
2025-05-16 17:33:13,302 - root - INFO - Processing batch 118/1130
2025-05-16 17:33:22,525 - root - INFO - Processing batch 119/1130
2025-05-16 17:33:31,930 - root - INFO - Processing batch 120/1130
2025-05-16 17:33:39,356 - root - INFO - Processing batch 121/1130
2025-05-16 17:33:47,797 - root - INFO - Processing batch 122/1130
2025-05-16 17:33:57,093 - root - INFO - Processing batch 123/1130
2025-05-16 17:34:06,910 - root - INFO - Processing batch 124/1130
2025-05-16 17:34:15,813 - root - INFO - Processing batch 125/1130
2025-05-16 17:34:19,192 - openai._base_client - INFO - Retrying request to /chat/completions in 0.463687 seconds
2025-05-16 17:34:29,899 - root - INFO - Processing batch 126/1130
2025-05-16 17:34:42,770 - root - INFO - Processing batch 127/1130
2025-05-16 17:34:51,533 - root - INFO - Processing batch 128/1130
2025-05-16 17:35:01,862 - root - INFO - Processing batch 129/1130
2025-05-16 17:35:09,185 - root - INFO - Processing batch 130/1130
2025-05-16 17:35:18,686 - root - INFO - Processing batch 131/1130
2025-05-16 17:35:30,162 - root - INFO - Processing batch 132/1130
2025-05-16 17:35:39,035 - root - INFO - Processing batch 133/1130
2025-05-16 17:35:50,013 - root - INFO - Processing batch 134/1130
2025-05-16 17:35:58,486 - root - INFO - Processing batch 135/1130
2025-05-16 17:36:07,357 - root - INFO - Processing batch 136/1130
2025-05-16 17:36:17,852 - root - INFO - Processing batch 137/1130
2025-05-16 17:36:29,670 - root - INFO - Processing batch 138/1130
2025-05-16 17:36:38,154 - root - INFO - Processing batch 139/1130
2025-05-16 17:36:47,672 - root - INFO - Processing batch 140/1130
2025-05-16 17:36:55,804 - root - INFO - Processing batch 141/1130
2025-05-16 17:37:06,218 - root - INFO - Processing batch 142/1130
2025-05-16 17:37:20,655 - root - INFO - Processing batch 143/1130
2025-05-16 17:37:29,958 - root - INFO - Processing batch 144/1130
2025-05-16 17:37:37,354 - root - INFO - Processing batch 145/1130
2025-05-16 17:37:45,330 - root - INFO - Processing batch 146/1130
2025-05-16 17:37:57,130 - root - INFO - Processing batch 147/1130
2025-05-16 17:38:07,061 - root - INFO - Processing batch 148/1130
2025-05-16 17:38:16,826 - root - INFO - Processing batch 149/1130
2025-05-16 17:38:24,765 - root - INFO - Processing batch 150/1130
2025-05-16 17:38:35,000 - root - INFO - Processing batch 151/1130
2025-05-16 17:38:44,954 - root - INFO - Processing batch 152/1130
2025-05-16 17:38:55,254 - root - INFO - Processing batch 153/1130
2025-05-16 17:39:04,947 - root - INFO - Processing batch 154/1130
2025-05-16 17:39:16,730 - root - INFO - Processing batch 155/1130
2025-05-16 17:39:25,525 - root - INFO - Processing batch 156/1130
2025-05-16 17:39:35,737 - root - INFO - Processing batch 157/1130
2025-05-16 17:39:44,235 - root - INFO - Processing batch 158/1130
2025-05-16 17:39:56,329 - root - INFO - Processing batch 159/1130
2025-05-16 17:40:08,104 - root - INFO - Processing batch 160/1130
2025-05-16 17:40:08,258 - openai._base_client - INFO - Retrying request to /chat/completions in 0.375618 seconds
2025-05-16 17:40:20,133 - root - INFO - Processing batch 161/1130
2025-05-16 17:40:30,033 - root - INFO - Processing batch 162/1130
2025-05-16 17:40:41,170 - root - INFO - Processing batch 163/1130
2025-05-16 17:40:52,535 - root - INFO - Processing batch 164/1130
2025-05-16 17:41:01,983 - root - INFO - Processing batch 165/1130
2025-05-16 17:41:10,940 - root - INFO - Processing batch 166/1130
2025-05-16 17:41:22,842 - root - INFO - Processing batch 167/1130
2025-05-16 17:41:32,838 - root - INFO - Processing batch 168/1130
2025-05-16 17:41:47,168 - root - INFO - Processing batch 169/1130
2025-05-16 17:41:57,290 - root - INFO - Processing batch 170/1130
2025-05-16 17:42:02,787 - openai._base_client - INFO - Retrying request to /chat/completions in 0.494830 seconds
2025-05-16 17:42:08,612 - root - INFO - Processing batch 171/1130
2025-05-16 17:42:22,774 - root - INFO - Processing batch 172/1130
2025-05-16 17:42:31,092 - root - INFO - Processing batch 173/1130
2025-05-16 17:42:43,247 - root - INFO - Processing batch 174/1130
2025-05-16 17:42:51,240 - root - INFO - Processing batch 175/1130
2025-05-16 17:42:59,493 - root - INFO - Processing batch 176/1130
2025-05-16 17:43:09,801 - root - INFO - Processing batch 177/1130
2025-05-16 17:43:17,622 - root - INFO - Processing batch 178/1130
2025-05-16 17:43:27,997 - root - INFO - Processing batch 179/1130
2025-05-16 17:43:36,434 - root - INFO - Processing batch 180/1130
2025-05-16 17:43:58,618 - root - INFO - Processing batch 181/1130
2025-05-16 17:44:07,566 - root - INFO - Processing batch 182/1130
2025-05-16 17:44:15,614 - root - INFO - Processing batch 183/1130
2025-05-16 17:44:30,547 - root - INFO - Processing batch 184/1130
2025-05-16 17:44:39,252 - root - INFO - Processing batch 185/1130
2025-05-16 17:44:48,508 - root - INFO - Processing batch 186/1130
2025-05-16 17:44:58,528 - root - INFO - Processing batch 187/1130
2025-05-16 17:45:07,079 - root - INFO - Processing batch 188/1130
2025-05-16 17:45:17,794 - root - INFO - Processing batch 189/1130
2025-05-16 17:45:27,372 - root - INFO - Processing batch 190/1130
2025-05-16 17:45:36,341 - root - INFO - Processing batch 191/1130
2025-05-16 17:45:46,062 - root - INFO - Processing batch 192/1130
2025-05-16 17:45:54,706 - root - INFO - Processing batch 193/1130
2025-05-16 17:46:04,023 - root - INFO - Processing batch 194/1130
2025-05-16 17:46:14,470 - root - INFO - Processing batch 195/1130
2025-05-16 17:46:28,511 - root - INFO - Processing batch 196/1130
2025-05-16 17:46:38,705 - root - INFO - Processing batch 197/1130
2025-05-16 17:46:47,961 - root - INFO - Processing batch 198/1130
2025-05-16 17:47:00,495 - root - INFO - Processing batch 199/1130
2025-05-16 17:47:07,838 - openai._base_client - INFO - Retrying request to /chat/completions in 0.460092 seconds
2025-05-16 17:47:13,288 - root - INFO - Processing batch 200/1130
2025-05-16 17:47:24,609 - root - INFO - Processing batch 201/1130
2025-05-16 17:47:36,123 - root - INFO - Processing batch 202/1130
2025-05-16 17:47:46,262 - root - INFO - Processing batch 203/1130
2025-05-16 17:48:34,477 - root - INFO - Processing batch 204/1130
2025-05-16 17:48:48,230 - root - INFO - Processing batch 205/1130
2025-05-16 17:48:57,469 - root - INFO - Processing batch 206/1130
2025-05-16 17:49:07,276 - root - INFO - Processing batch 207/1130
2025-05-16 17:49:18,018 - root - INFO - Processing batch 208/1130
2025-05-16 17:49:27,913 - root - INFO - Processing batch 209/1130
2025-05-16 17:49:36,631 - root - INFO - Processing batch 210/1130
2025-05-16 17:49:44,412 - root - INFO - Processing batch 211/1130
2025-05-16 17:49:54,182 - root - INFO - Processing batch 212/1130
2025-05-16 17:50:04,117 - root - INFO - Processing batch 213/1130
2025-05-16 17:50:14,440 - root - INFO - Processing batch 214/1130
2025-05-16 17:50:23,125 - root - INFO - Processing batch 215/1130
2025-05-16 17:50:33,558 - root - INFO - Processing batch 216/1130
2025-05-16 17:50:44,827 - root - INFO - Processing batch 217/1130
2025-05-16 17:50:57,249 - root - INFO - Processing batch 218/1130
2025-05-16 17:51:06,561 - root - INFO - Processing batch 219/1130
2025-05-16 17:51:16,211 - root - INFO - Processing batch 220/1130
2025-05-16 17:51:29,845 - root - INFO - Processing batch 221/1130
2025-05-16 17:51:39,200 - root - INFO - Processing batch 222/1130
2025-05-16 17:51:46,940 - root - INFO - Processing batch 223/1130
2025-05-16 17:51:59,450 - root - INFO - Processing batch 224/1130
2025-05-16 17:52:09,202 - root - INFO - Processing batch 225/1130
2025-05-16 17:52:17,196 - root - INFO - Processing batch 226/1130
2025-05-16 17:52:24,845 - root - INFO - Processing batch 227/1130
2025-05-16 17:52:32,841 - root - INFO - Processing batch 228/1130
2025-05-16 17:52:50,971 - root - INFO - Processing batch 229/1130
2025-05-16 17:52:59,949 - root - INFO - Processing batch 230/1130
2025-05-16 17:53:08,606 - root - INFO - Processing batch 231/1130
2025-05-16 17:53:52,481 - root - INFO - Processing batch 232/1130
2025-05-16 17:54:02,038 - root - INFO - Processing batch 233/1130
2025-05-16 17:54:12,499 - root - INFO - Processing batch 234/1130
2025-05-16 17:54:21,467 - root - INFO - Processing batch 235/1130
2025-05-16 17:54:29,915 - root - INFO - Processing batch 236/1130
2025-05-16 17:54:41,794 - root - INFO - Processing batch 237/1130
2025-05-16 17:54:49,688 - root - INFO - Processing batch 238/1130
2025-05-16 17:54:56,873 - root - INFO - Processing batch 239/1130
2025-05-16 17:55:04,808 - root - INFO - Processing batch 240/1130
2025-05-16 17:55:13,250 - root - INFO - Processing batch 241/1130
2025-05-16 17:55:22,217 - root - INFO - Processing batch 242/1130
2025-05-16 17:55:30,942 - root - INFO - Processing batch 243/1130
2025-05-16 17:55:41,256 - root - INFO - Processing batch 244/1130
2025-05-16 17:55:48,852 - root - INFO - Processing batch 245/1130
2025-05-16 17:55:57,180 - root - INFO - Processing batch 246/1130
2025-05-16 17:56:05,104 - root - INFO - Processing batch 247/1130
2025-05-16 17:56:14,847 - root - INFO - Processing batch 248/1130
2025-05-16 17:56:23,743 - root - INFO - Processing batch 249/1130
2025-05-16 17:56:32,664 - root - INFO - Processing batch 250/1130
2025-05-16 17:56:40,698 - root - INFO - Processing batch 251/1130
2025-05-16 17:56:55,608 - root - INFO - Processing batch 252/1130
2025-05-16 17:57:04,437 - root - INFO - Processing batch 253/1130
2025-05-16 17:57:11,073 - root - INFO - Processing batch 254/1130
2025-05-16 17:57:19,898 - root - INFO - Processing batch 255/1130
2025-05-16 17:57:29,156 - root - INFO - Processing batch 256/1130
2025-05-16 17:57:37,008 - root - INFO - Processing batch 257/1130
2025-05-16 17:57:46,998 - root - INFO - Processing batch 258/1130
2025-05-16 17:57:55,524 - root - INFO - Processing batch 259/1130
2025-05-16 17:58:03,006 - root - INFO - Processing batch 260/1130
2025-05-16 17:58:10,828 - root - INFO - Processing batch 261/1130
2025-05-16 17:58:19,186 - root - INFO - Processing batch 262/1130
2025-05-16 17:58:27,703 - root - INFO - Processing batch 263/1130
2025-05-16 17:58:37,490 - root - INFO - Processing batch 264/1130
2025-05-16 17:58:45,896 - root - INFO - Processing batch 265/1130
2025-05-16 17:58:56,149 - root - INFO - Processing batch 266/1130
2025-05-16 17:59:06,692 - root - INFO - Processing batch 267/1130
2025-05-16 17:59:15,979 - root - INFO - Processing batch 268/1130
2025-05-16 17:59:36,389 - root - INFO - Processing batch 269/1130
2025-05-16 17:59:44,473 - root - INFO - Processing batch 270/1130
2025-05-16 17:59:52,112 - root - INFO - Processing batch 271/1130
2025-05-16 18:00:03,834 - root - INFO - Processing batch 272/1130
2025-05-16 18:00:14,558 - root - INFO - Processing batch 273/1130
2025-05-16 18:00:24,753 - root - INFO - Processing batch 274/1130
2025-05-16 18:00:35,582 - root - INFO - Processing batch 275/1130
2025-05-16 18:00:46,573 - root - INFO - Processing batch 276/1130
2025-05-16 18:00:59,019 - root - INFO - Processing batch 277/1130
2025-05-16 18:01:07,078 - root - INFO - Processing batch 278/1130
2025-05-16 18:01:17,840 - root - INFO - Processing batch 279/1130
2025-05-16 18:01:26,972 - root - INFO - Processing batch 280/1130
2025-05-16 18:01:36,162 - root - INFO - Processing batch 281/1130
2025-05-16 18:01:46,771 - root - INFO - Processing batch 282/1130
2025-05-16 18:01:55,693 - root - INFO - Processing batch 283/1130
2025-05-16 18:02:14,123 - root - INFO - Processing batch 284/1130
2025-05-16 18:02:22,040 - root - INFO - Processing batch 285/1130
2025-05-16 18:02:30,651 - root - INFO - Processing batch 286/1130
2025-05-16 18:02:37,952 - root - INFO - Processing batch 287/1130
2025-05-16 18:02:45,873 - root - INFO - Processing batch 288/1130
2025-05-16 18:02:56,547 - root - INFO - Processing batch 289/1130
2025-05-16 18:03:06,221 - root - INFO - Processing batch 290/1130
2025-05-16 18:03:13,643 - root - INFO - Processing batch 291/1130
2025-05-16 18:03:58,551 - root - INFO - Processing batch 292/1130
2025-05-16 18:07:31,450 - openai._base_client - INFO - Retrying request to /chat/completions in 0.460127 seconds
2025-05-16 18:07:36,771 - root - INFO - Processing batch 293/1130
2025-05-16 18:07:48,065 - root - INFO - Processing batch 294/1130
2025-05-16 18:07:56,775 - root - INFO - Processing batch 295/1130
2025-05-16 18:08:07,913 - root - INFO - Processing batch 296/1130

## Tidy up the extracted data before upload

In [5]:
output_df = pd.read_json("afs_open_alex_scan_2.jsonl", lines=True)
output_df

,is_relevant,is_relevant_reason,programme_name,summary,child_outcomes_targeted,child_outcomes_category,parent_outcomes_targeted,parent_outcomes_category,digital_component,digital_component_description,...,barriers_to_engagement,other_engagement_learnings,study_type,programme_evaluation_desc,evidence_of_effectiveness,limitations,id,timestamp,model,temperature
0,no,The programme targets adolescent girls pre-pre...,Ntshembo intervention,A community-based health promotion interventio...,[N/A],[N/A],[N/A],[N/A],no,N/A,...,[],[],i,N/A,[],[],https://openalex.org/W2113761365,2025-05-16 16:04:58.393144+00:00,gpt-4.1-mini,0
1,no,The programme targets parents of children aged...,Sexuality Education Intervention for Parents o...,A two-week sexuality education intervention ai...,[sexuality education knowledge],[N/A],"[attitude and beliefs, sexual communication, k...","[Parental beliefs and knowledge, Parental beha...",no,N/A,...,[],[],b,Within-subjects design with 15 parents receivi...,"[Significant improvements in attitude, beliefs...","[Small sample size (15 parents), No control gr...",https://openalex.org/W2951570962,2025-05-16 16:04:58.394702+00:00,gpt-4.1-mini,0
2,no,The text focuses on vaccination refusal and pe...,N/A,N/A,[],[N/A],[],[N/A],no,N/A,...,[],[],i,N/A,[],[],https://openalex.org/W3048469179,2025-05-16 16:04:58.395090+00:00,gpt-4.1-mini,0
3,no,The text describes a broad public health inter...,N/A,N/A,[],[],[],[],no,N/A,...,[],[],i,The Intervention Wheel model was subjected to ...,[The critique process established the validity...,[],https://openalex.org/W2043137199,2025-05-16 16:04:58.395247+00:00,gpt-4.1-mini,0
4,no,The text is a study examining associations amo...,N/A,N/A,[],[],[],[],no,N/A,...,[],[],c,Observational and self-report measures with 83...,[],[],https://openalex.org/W2134310657,2025-05-16 16:04:58.395356+00:00,gpt-4.1-mini,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34140,no,The text analyzes single fathers' child-care t...,N/A,N/A,[],[],[],[],no,N/A,...,[],[],c,Analysis of nationally representative American...,[],[],https://openalex.org/W2044699211,2025-05-16 20:16:56.569013+00:00,gpt-4.1-mini,0
34141,no,The text discusses the impact of suicide on fa...,N/A,N/A,[],[N/A],[],[N/A],no,N/A,...,[],[],i,N/A,[],[],https://openalex.org/W2098758147,2025-05-16 20:16:56.570124+00:00,gpt-4.1-mini,0
34142,no,The text is a systematic review about maternal...,N/A,N/A,[N/A],[N/A],[N/A],[N/A],no,N/A,...,[N/A],[N/A],h,Systematic literature review of 14 articles ex...,[Mixed findings: no association with children'...,[Findings are mixed; need for prospective desi...,https://openalex.org/W2592184171,2025-05-16 20:16:56.570407+00:00,gpt-4.1-mini,0
34143,no,The text focuses on parental caregivers of chi...,N/A,N/A,[],[],[],[],no,N/A,...,[],[],i,N/A,[],[],https://openalex.org/W2059170206,2025-05-16 20:16:56.570612+00:00,gpt-4.1-mini,0
34144,no,The text is a study on maternal depression and...,N/A,N/A,[],[N/A],[],[N/A],no,N/A,...,[],[],c,The study evaluated mother-infant interactive ...,[],[],https://openalex.org/W2130601615,2025-05-16 20:16:56.570813+00:00,gpt-4.1-mini,0

In [11]:
final_df = (
    output_df
    .query("is_relevant == 'yes' or is_about_engagement == 'yes'")
)

In [12]:
output_df['is_relevant'].value_counts()

is_relevant
no     30306
yes     3839
Name: count, dtype: int64

In [13]:
output_df.columns

Index(['is_relevant', 'is_relevant_reason', 'programme_name', 'summary',
       'child_outcomes_targeted', 'child_outcomes_category',
       'parent_outcomes_targeted', 'parent_outcomes_category',
       'digital_component', 'digital_component_description', 'country',
       'age_range', 'age_range_numerical', 'target_population',
       'disadvantaged_groups_engaged', 'is_about_engagement',
       'engagement_strategies', 'engagement_success', 'barriers_to_engagement',
       'other_engagement_learnings', 'study_type', 'programme_evaluation_desc',
       'evidence_of_effectiveness', 'limitations', 'id', 'timestamp', 'model',
       'temperature'],
      dtype='object')

In [7]:
# output_df.groupby(['is_relevant', 'programme_evaluation']).size().reset_index(name='counts')

In [17]:
final_cols = [
       'programme_name',
       'doi',   
       'publication_year',  
       'cited_by_count',     
       'is_relevant',
       'is_relevant_reason',    
       # programme       
       'summary',           
       'child_outcomes_targeted',
       'child_outcomes_category',
       'parent_outcomes_targeted',
       'parent_outcomes_category',
       # digital
       'digital_component',
       'digital_component_description',
       # context
       'country',
       'author_countries',
       'age_range',
       'age_range_numerical',
       'target_population',
       'disadvantaged_groups_engaged',
       # engagement
       'is_about_engagement',
       'engagement_strategies',
       'engagement_success',
       'barriers_to_engagement',
       'other_engagement_learnings',
       # study type
       'study_type',
       'programme_evaluation_desc',
       'evidence_of_effectiveness',
       'limitations',
       # other metadata
       'id',
       'title', 
       'text',       
]

In [19]:
df_checked = (
    pd.read_json("afs_open_alex_scan_2.jsonl", lines=True)
    .query("is_relevant == 'yes' or is_about_engagement == 'yes'")
    .merge(data_df[['id', 'publication_year', 'authorships', 'doi', 'title', 'text', 'is_retracted', 'cited_by_count']], on='id', how='left')
    .assign(
        author_countries = lambda df: df['authorships'].apply(extract_author_countries),
    )
    .assign(
        child_outcomes = lambda df: df['child_outcomes_targeted'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        child_outcomes_category = lambda df: df['child_outcomes_category'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        parent_outcomes = lambda df: df['parent_outcomes_targeted'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        parent_outcomes_category = lambda df: df['parent_outcomes_category'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        disadvantaged_groups_engaged = lambda df: df['disadvantaged_groups_engaged'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        engagement_strategies = lambda df: df['engagement_strategies'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        barriers_to_engagement = lambda df: df['barriers_to_engagement'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        evidence_of_effectiveness = lambda df: df['evidence_of_effectiveness'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        limitations = lambda df: df['limitations'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        other_learnings = lambda df: df['other_engagement_learnings'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
    )
    .query("is_retracted == False")
)[final_cols]

In [24]:
len(df_checked)

5084

In [23]:
extra_fields = [
        {"name": "doi", "description": "The DOI of the publication."},
        {"name": "cited_by_count", "description": "The number of times the publication has been cited."},
        {"name": "text", "description": "The text of the publication."},
        {"name": "publication_year", "description": "The year of publication."},
        {"name": "id", "description": "The unique identifier of the publication."},
        {"name": "title", "description": "The title of the publication."},
    ]
all_fields = fields + extra_fields

# Create a table with explanations of all the fields used in the output table (cols columns)
df_explanations = pd.DataFrame.from_records(all_fields).drop(columns=['type'])
# Order it in the same order as the columns in the output table
df_explanations = df_explanations.set_index('name').reindex(final_cols).reset_index()
df_explanations

,name,description
0,programme_name,The name of the programme or intervention.
1,doi,The DOI of the publication.
2,publication_year,The year of publication.
3,cited_by_count,The number of times the publication has been c...
4,is_relevant,One-word answer: 'yes' if the text is about a ...
5,is_relevant_reason,"Short explanation (one sentence, 20 words) of ..."
6,summary,A brief summary of what the programme involves...
7,child_outcomes_targeted,Child-related outcomes the programme seeks to ...
8,child_outcomes_category,Infer if the child-related outcomes are best c...
9,parent_outcomes_targeted,Parent-related outcomes the programme targets ...
10,parent_outcomes_category,Infer if the parent-related outcomes are best ...
11,digital_component,One-word answer: 'yes' if programme includes a...
12,digital_component_description,"Brief description of the digital component, if..."
13,country,The country or countries where the programme w...
14,author_countries,NaN
15,age_range,The programme is aimed at parents of what age ...
16,age_range_numerical,Infer the probable age range in years and in n...
17,target_population,Description of the parent population the progr...
18,disadvantaged_groups_engaged,List of any specific disadvantaged groups the ...
19,is_about_engagement,One-word answer: 'yes' if the text is specific...
20,engagement_strategies,"Recruitment and engagement strategies used, if..."
21,engagement_success,Any information about how successful the engag...
22,barriers_to_engagement,Barriers or challenges mentioned regarding rec...
23,other_engagement_learnings,"Other useful insights about recruitment, or en..."
24,study_type,"If possible, identify the type of study. Provi..."
25,programme_evaluation_desc,Description of how the programme was evaluated.
26,evidence_of_effectiveness,"Evidence of outcomes, effectiveness, or evalua..."
27,limitations,Any limitations of the programme or study ment...
28,id,The unique identifier of the publication.
29,title,The title of the publication.
30,text,The text of the publication.

## Upload to Google Sheets (NB: don't overwrite)

In [ ]:
# commented out for now, so that it doesn't overwrite by accident as the data is already uploaded
# from discovery_utils.utils import (
#     google
# )
# sheet_id = "18IHEOjdyyGejZ5SFFcfKYfgCFTjNp9k_-bChT0PRlLU"

In [29]:
google.upload_data_to_gsheet(sheet_id, {"data": df_checked})
google.format_gsheet(sheet_id, "data", freeze_cols=2)

2025-05-19 15:59:22,661 - root - INFO - Connected to Google Sheet: Review of strategies to engage disadvantaged families in parenting interventions [19-05-2025]
2025-05-19 15:59:25,256 - root - INFO - Uploading DataFrame to sheet: data
/Users/karlis.kanders/Code/discovery_utils/.venv/lib/python3.12/site-packages/df2gspread/df2gspread.py:138: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str)
/Users/karlis.kanders/Code/discovery_utils/.venv/lib/python3.12/site-packages/df2gspread/df2gspread.py:138: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str)
2025-05-19 16:01:12,149 - root - INFO - Upload completed successfully.
2025-05-19 16:01:22,069 - root - INFO - Connected to Google Sheet: Review of strategies to engage disadvantaged families in parenting interventions [19-05-2025]

In [30]:
google.upload_data_to_gsheet(sheet_id, {"columns": df_explanations})
google.format_gsheet(sheet_id, "columns", freeze_cols=0)

2025-05-19 16:01:33,087 - root - INFO - Connected to Google Sheet: Review of strategies to engage disadvantaged families in parenting interventions [19-05-2025]
2025-05-19 16:01:35,245 - root - INFO - Uploading DataFrame to sheet: columns
/Users/karlis.kanders/Code/discovery_utils/.venv/lib/python3.12/site-packages/df2gspread/df2gspread.py:138: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str)
/Users/karlis.kanders/Code/discovery_utils/.venv/lib/python3.12/site-packages/df2gspread/df2gspread.py:138: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str)
2025-05-19 16:01:48,376 - root - INFO - Upload completed successfully.
2025-05-19 16:01:50,158 - root - INFO - Connected to Google Sheet: Review of strategies to engage disadvantaged families in parenting interventions [19-05-2025]