# Using the data for network building

In [1]:
import pandas as pd
from discovery_utils.utils.llm import batch_check

import pandas as pd
import os

# Alternative: s3://discovery-iss/data/afs_scanning/afs_open_alex_scan_parenting_interventions.csv
INPUT_DATA = 'afs_open_alex_scan_parenting_interventions.csv'

data_df = (
    pd.read_csv(INPUT_DATA)
    .query("publication_year >= 2000")
    .assign(text = lambda df: df['title'] + ' ' + df['abstract'])
)
len(data_df)

# testing on a smaller sample for now
# data_df = data_df.sample(100, random_state=42)

34145

In [2]:
relevant_df = (
    pd.read_json("afs_open_alex_scan_2.jsonl", lines=True)
    .query("is_relevant == 'yes'")
)

In [3]:
from ast import literal_eval

def extract_author_countries(authorships):
    try:
        # Convert the string representation of the list to an actual list
        authors = literal_eval(authorships)
        countries = []
        for author in authors:
            for institution in author.get('institutions', []):
                if 'country_code' in institution:
                    countries.append(institution['country_code'])
        # remove null values
        countries = [country for country in countries if country is not None]
        return sorted(list(set(countries)))
    except (ValueError, SyntaxError):
        # Handle the case where the string cannot be evaluated
        return []

## Run the LLM pipeline

In [4]:
_data_df = data_df.query("id in @relevant_df.id.tolist()")
ids = _data_df.id.tolist()
text = data_df.text.tolist()
test_data = dict(zip(ids, text))

In [5]:
len(test_data)

3839

In [6]:
system_message_pass1 = """
    Extract structured information about the main results of the intervention from the provided text.

    The intervention could be relevant to developmental, behavioural, or well-being outcomes
    such as children language development, cognitive development, social-emotional skills, physical and mental health, or
    parental outcomes such as confidence, skills, behaviours, knowledge, self-efficacy, and well-being.
    
    Unless requested otherwise, adhere as precisely as possible to the language and text that is used in the provided text document.
    
    If the requested information is not described, return N/A. DO NOT make up any false information or false inferences.
"""

fields_pass1 = [
    # Relevance
    # {"name": "main_results", "type": "list[str]", "description": "List of each of the main results of the study, for example: ['parenting education decreased child mental health problems',...]"},
    {"name": "main_results", "type": "list[str]", "description": "Succinctly extract the main intervention and its result of the study; an intervention means that there was an intervention or predictor variable that was manipulated, and an outcome variable - succinctly describe those in one short sentence. If there are more than one main intervention, extract more - but extract only those that are the focus of the paper."},
    {"name": "sample_size", "type": "list[int]", "description": "Number of participants in the study. If there are multiple samples, provide the sample size for each."},
]

In [7]:
processor = batch_check.LLMProcessor(
    model_name="gpt-4.1-mini",
    # model_name="gpt-4o-mini",
    temperature=0,
    output_path="pet_scan_3.jsonl",
    system_message=system_message_pass1,
    session_name="pet_scan",
    output_fields=fields_pass1,
)

processor.run(test_data, batch_size=30, sleep_time=0.5)

2025-05-20 00:33:35,219 - root - INFO - Using OpenAI

2025-05-20 00:33:35,297 - root - INFO - Processing batch 1/123
2025-05-20 00:33:39,713 - root - INFO - Processing batch 2/123
2025-05-20 00:33:46,472 - root - INFO - Processing batch 3/123
2025-05-20 00:33:50,400 - root - INFO - Processing batch 4/123
2025-05-20 00:33:55,705 - root - INFO - Processing batch 5/123
2025-05-20 00:33:59,456 - root - INFO - Processing batch 6/123
2025-05-20 00:34:06,367 - root - INFO - Processing batch 7/123
2025-05-20 00:34:10,243 - root - INFO - Processing batch 8/123
2025-05-20 00:34:14,951 - root - INFO - Processing batch 9/123
2025-05-20 00:34:18,754 - root - INFO - Processing batch 10/123
2025-05-20 00:34:22,715 - root - INFO - Processing batch 11/123
2025-05-20 00:34:27,309 - root - INFO - Processing batch 12/123
2025-05-20 00:34:32,417 - root - INFO - Processing batch 13/123
2025-05-20 00:34:36,003 - root - INFO - Processing batch 14/123
2025-05-20 00:34:39,050 - root - INFO - Processing batch 15/123
2025-05-20 00:34:43,409 - root - INFO - Processing batch 16/123
2025-05-20 00:34:47,337 - root - INFO - Processing batch 17/123
2025-05-20 00:34:51,945 - root - INFO - Processing batch 18/123
2025-05-20 00:34:56,733 - root - INFO - Processing batch 19/123
2025-05-20 00:35:00,695 - root - INFO - Processing batch 20/123
2025-05-20 00:35:03,666 - root - INFO - Processing batch 21/123
2025-05-20 00:35:07,041 - root - INFO - Processing batch 22/123
2025-05-20 00:35:10,507 - root - INFO - Processing batch 23/123
2025-05-20 00:35:15,219 - root - INFO - Processing batch 24/123
2025-05-20 00:35:18,494 - root - INFO - Processing batch 25/123
2025-05-20 00:35:24,141 - root - INFO - Processing batch 26/123
2025-05-20 00:35:29,410 - root - INFO - Processing batch 27/123
2025-05-20 00:35:33,287 - root - INFO - Processing batch 28/123
2025-05-20 00:35:42,037 - root - INFO - Processing batch 29/123
2025-05-20 00:35:45,209 - root - INFO - Processing batch 30/123
2025-05-20 00:35:48,565 - root - INFO - Processing batch 31/123
2025-05-20 00:35:53,879 - root - INFO - Processing batch 32/123
2025-05-20 00:35:56,702 - root - INFO - Processing batch 33/123
2025-05-20 00:36:01,443 - root - INFO - Processing batch 34/123
2025-05-20 00:36:04,370 - root - INFO - Processing batch 35/123
2025-05-20 00:36:08,235 - root - INFO - Processing batch 36/123
2025-05-20 00:36:12,301 - root - INFO - Processing batch 37/123
2025-05-20 00:36:17,069 - root - INFO - Processing batch 38/123
2025-05-20 00:36:21,240 - root - INFO - Processing batch 39/123
2025-05-20 00:36:27,860 - root - INFO - Processing batch 40/123
2025-05-20 00:36:32,954 - root - INFO - Processing batch 41/123
2025-05-20 00:36:37,901 - root - INFO - Processing batch 42/123
2025-05-20 00:36:42,249 - root - INFO - Processing batch 43/123
2025-05-20 00:36:45,457 - root - INFO - Processing batch 44/123
2025-05-20 00:36:49,222 - root - INFO - Processing batch 45/123
2025-05-20 00:36:53,245 - root - INFO - Processing batch 46/123
2025-05-20 00:36:59,271 - root - INFO - Processing batch 47/123
2025-05-20 00:37:03,235 - root - INFO - Processing batch 48/123
2025-05-20 00:37:07,586 - root - INFO - Processing batch 49/123
2025-05-20 00:37:12,665 - root - INFO - Processing batch 50/123
2025-05-20 00:37:20,089 - root - INFO - Processing batch 51/123
2025-05-20 00:37:23,826 - root - INFO - Processing batch 52/123
2025-05-20 00:37:27,499 - root - INFO - Processing batch 53/123
2025-05-20 00:37:31,659 - root - INFO - Processing batch 54/123
2025-05-20 00:37:34,940 - root - INFO - Processing batch 55/123
2025-05-20 00:37:38,675 - root - INFO - Processing batch 56/123
2025-05-20 00:37:41,961 - root - INFO - Processing batch 57/123
2025-05-20 00:37:45,736 - root - INFO - Processing batch 58/123
2025-05-20 00:37:49,812 - root - INFO - Processing batch 59/123
2025-05-20 00:37:57,063 - root - INFO - Processing batch 60/123
2025-05-20 00:38:00,890 - root - INFO - Processing batch 61/123
2025-05-20 00:38:06,412 - root - INFO - Processing batch 62/123
2025-05-20 00:38:10,218 - root - INFO - Processing batch 63/123
2025-05-20 00:38:14,258 - root - INFO - Processing batch 64/123
2025-05-20 00:38:19,083 - root - INFO - Processing batch 65/123
2025-05-20 00:38:23,280 - root - INFO - Processing batch 66/123
2025-05-20 00:38:27,333 - root - INFO - Processing batch 67/123
2025-05-20 00:38:33,611 - root - INFO - Processing batch 68/123
2025-05-20 00:38:36,868 - root - INFO - Processing batch 69/123
2025-05-20 00:38:41,685 - root - INFO - Processing batch 70/123
2025-05-20 00:38:47,310 - root - INFO - Processing batch 71/123
2025-05-20 00:38:50,246 - root - INFO - Processing batch 72/123
2025-05-20 00:38:54,753 - root - INFO - Processing batch 73/123
2025-05-20 00:38:58,260 - root - INFO - Processing batch 74/123
2025-05-20 00:39:01,537 - root - INFO - Processing batch 75/123
2025-05-20 00:39:05,844 - root - INFO - Processing batch 76/123
2025-05-20 00:39:09,517 - root - INFO - Processing batch 77/123
2025-05-20 00:39:12,830 - root - INFO - Processing batch 78/123
2025-05-20 00:39:16,598 - root - INFO - Processing batch 79/123
2025-05-20 00:39:19,901 - root - INFO - Processing batch 80/123
2025-05-20 00:39:24,589 - root - INFO - Processing batch 81/123
2025-05-20 00:39:28,610 - root - INFO - Processing batch 82/123
2025-05-20 00:39:31,943 - root - INFO - Processing batch 83/123
2025-05-20 00:39:37,130 - root - INFO - Processing batch 84/123
2025-05-20 00:39:40,796 - root - INFO - Processing batch 85/123
2025-05-20 00:39:45,029 - root - INFO - Processing batch 86/123
2025-05-20 00:39:49,084 - root - INFO - Processing batch 87/123
2025-05-20 00:39:53,268 - root - INFO - Processing batch 88/123
2025-05-20 00:39:57,691 - root - INFO - Processing batch 89/123
2025-05-20 00:40:03,546 - root - INFO - Processing batch 90/123
2025-05-20 00:40:07,158 - root - INFO - Processing batch 91/123
2025-05-20 00:40:11,011 - root - INFO - Processing batch 92/123
2025-05-20 00:40:14,827 - root - INFO - Processing batch 93/123
2025-05-20 00:40:19,385 - root - INFO - Processing batch 94/123
2025-05-20 00:40:23,306 - root - INFO - Processing batch 95/123
2025-05-20 00:40:29,043 - root - INFO - Processing batch 96/123
2025-05-20 00:40:33,492 - root - INFO - Processing batch 97/123
2025-05-20 00:40:37,438 - root - INFO - Processing batch 98/123
2025-05-20 00:40:41,663 - root - INFO - Processing batch 99/123
2025-05-20 00:40:45,250 - root - INFO - Processing batch 100/123
2025-05-20 00:40:48,807 - root - INFO - Processing batch 101/123
2025-05-20 00:40:52,562 - root - INFO - Processing batch 102/123
2025-05-20 00:40:56,752 - root - INFO - Processing batch 103/123
2025-05-20 00:41:00,641 - root - INFO - Processing batch 104/123
2025-05-20 00:41:05,669 - root - INFO - Processing batch 105/123
2025-05-20 00:41:09,485 - root - INFO - Processing batch 106/123
2025-05-20 00:41:14,064 - root - INFO - Processing batch 107/123
2025-05-20 00:41:18,493 - root - INFO - Processing batch 108/123
2025-05-20 00:41:23,742 - root - INFO - Processing batch 109/123
2025-05-20 00:41:27,595 - root - INFO - Processing batch 110/123
2025-05-20 00:41:30,828 - root - INFO - Processing batch 111/123
2025-05-20 00:41:34,549 - root - INFO - Processing batch 112/123
2025-05-20 00:41:40,689 - root - INFO - Processing batch 113/123
2025-05-20 00:41:44,210 - root - INFO - Processing batch 114/123
2025-05-20 00:41:48,401 - root - INFO - Processing batch 115/123
2025-05-20 00:41:53,089 - root - INFO - Processing batch 116/123
2025-05-20 00:41:57,209 - root - INFO - Processing batch 117/123
2025-05-20 00:42:02,770 - root - INFO - Processing batch 118/123
2025-05-20 00:42:06,622 - root - INFO - Processing batch 119/123
2025-05-20 00:42:11,256 - root - INFO - Processing batch 120/123
2025-05-20 00:42:14,777 - root - INFO - Processing batch 121/123
2025-05-20 00:42:20,281 - root - INFO - Processing batch 122/123
2025-05-20 00:42:26,493 - root - INFO - Processing batch 123/123

In [8]:
output_df = pd.read_json("pet_scan_3.jsonl", lines=True)
output_df

,main_results,sample_size,id,timestamp,model,temperature
0,[Implementation of nationwide school closures ...,[220000000],https://openalex.org/W2160124959,2025-05-19 23:00:33.588303+00:00,gpt-4.1-mini,0
1,[Implementation of a coproduced family centere...,"[3106, 2148, 435, 203, 586]",https://openalex.org/W1982264918,2025-05-19 23:00:33.590514+00:00,gpt-4.1-mini,0
2,[Early Head Start improved 3-year-old children...,[3001],https://openalex.org/W2066202980,2025-05-19 23:00:33.590615+00:00,gpt-4.1-mini,0
3,[Home- and center-based programs with a parent...,[0],https://openalex.org/W2116341692,2025-05-19 23:00:33.590684+00:00,gpt-4.1-mini,0
4,[Parent-implemented language interventions sig...,[18],https://openalex.org/W2058887279,2025-05-19 23:00:33.590746+00:00,gpt-4.1-mini,0
...,...,...,...,...,...,...
3834,"[Infants engage in rhythmic, musical-like dial...",[],https://openalex.org/W2030543951,2025-05-19 23:42:26.497308+00:00,gpt-4.1-mini,0
3835,[Assertive community treatment (ACT) tailored ...,[35],https://openalex.org/W2149642767,2025-05-19 23:42:26.497440+00:00,gpt-4.1-mini,0
3836,[An individualized DIR/FloortimeTM-based inter...,[25],https://openalex.org/W1973779798,2025-05-19 23:42:26.497577+00:00,gpt-4.1-mini,0
3837,[The study identified substantial and heteroge...,[44],https://openalex.org/W2145116009,2025-05-19 23:42:26.497716+00:00,gpt-4.1-mini,0
3838,"[The eHealth Behavior Management Model, combin...",[0],https://openalex.org/W2078079190,2025-05-19 23:42:26.497857+00:00,gpt-4.1-mini,0

In [9]:
from pydantic import BaseModel, Field
from discovery_utils.utils.llm import llm_utils
import importlib
import tiktoken
importlib.reload(tiktoken)
importlib.reload(llm_utils)

prompt = {
    "system_message": """
        You are an expert researcher.
        Extract structured information about the intervention result from the provided text.
        Unless requested otherwise, adhere as precisely as possible to the language and text that is used in the provided text document.
        Keep your extractions as short as possible, but include all relevant information.
        If the requested information is not described, return N/A. DO NOT make up any false information or false inferences.
    """,
    "user_message": """
        The specific intervention result we are interested in is the following: {result}
        \n\n
        The text is the following: {input}
    """,
}

class ResultModel(BaseModel):
    intervention_variable: str = Field(description="The intervention or predictor variable (i.e., what was manipulated or used as a predictor)")
    outcome_variable: str = Field(description="The outcome variable (i.e., what was measured or predicted)")
    effect_size: str = Field(description="The effect size of the intervention (if available, otherwise N/A)")
    effect_size_number: float = Field(description="The effect size of the intervention (if available, otherwise N/A)")
    effect_size_type: str = Field(description="The effect size type for this main result (e.g. odds ratio, difference of means)")
    uncertainty: str = Field(description="The estimate of uncertainty in the effect size (e.g. s.e., 95% CI)")
    p_value: str = Field(description="The p-value of the effect size (if available, otherwise N/A)")
    effect_sign: str = Field(description="The direction of the effect, choose ONE of the following: intervention increases the outcome=POSITIVE, intervention decreases the outcome=NEGATIVE, no effect=NONE, unknown=N/A)")

Generator = llm_utils.StructuredOutputGenerator(
    model_dict={"model_name": "gpt-4.1-mini", "temperature": 0, "max_tokens": 120000},
    output_class=ResultModel,
    prompts=prompt,
    check_token_length=False,
)


def extract_result_data(result: str, text: str):
    """Classify the relevance of a text to a given mission.

    Uses mission scope definitions in the configuration file
    Args:
        input: The input text to classify.
        mission: The mission to classify the text against.

    Returns:
        RelevanceClassifier: The classification result.
    """
    return Generator.generate({"result": result, "input": text})

2025-05-20 00:45:36,244 - root - INFO - Using OpenAI

In [14]:
result_datas = []
for i, row in output_df.iterrows():
    if i <= 1714:
        continue
    print(f"{i}/{len(output_df)}")
    main_results = row['main_results']
    for result in main_results:
        result_data = extract_result_data(result, test_data[row['id']])
        result_datas.append({"id": row['id'], "result": result, **result_data.model_dump()})
result_df = pd.DataFrame(result_datas)

1715/3839
1716/3839
1717/3839
1718/3839
1719/3839
1720/3839
1721/3839
1722/3839
1723/3839
1724/3839
1725/3839
1726/3839
1727/3839
1728/3839
1729/3839
1730/3839
1731/3839
1732/3839
1733/3839
1734/3839
1735/3839
1736/3839
1737/3839
1738/3839
1739/3839
1740/3839
1741/3839
1742/3839
1743/3839
1744/3839
1745/3839
1746/3839
1747/3839
1748/3839
1749/3839
1750/3839
1751/3839
1752/3839
1753/3839
1754/3839
1755/3839
1756/3839
1757/3839
1758/3839
1759/3839
1760/3839
1761/3839
1762/3839
1763/3839
1764/3839
1765/3839
1766/3839
1767/3839
1768/3839
1769/3839
1770/3839
1771/3839
1772/3839
1773/3839
1774/3839
1775/3839
1776/3839
1777/3839
1778/3839
1779/3839
1780/3839
1781/3839
1782/3839
1783/3839
1784/3839
1785/3839
1786/3839
1787/3839
1788/3839
1789/3839
1790/3839
1791/3839
1792/3839
1793/3839
1794/3839
1795/3839
1796/3839
1797/3839
1798/3839
1799/3839
1800/3839
1801/3839
1802/3839
1803/3839
1804/3839
1805/3839
1806/3839
1807/3839
1808/3839
1809/3839
1810/3839
1811/3839
1812/3839
1813/3839
1814/3839
1815/3839
1816/3839
1817/3839
1818/3839
1819/3839
1820/3839
1821/3839
1822/3839
1823/3839
1824/3839
1825/3839
1826/3839
1827/3839
1828/3839
1829/3839
1830/3839
1831/3839
1832/3839
1833/3839
1834/3839
1835/3839
1836/3839
1837/3839
1838/3839
1839/3839
1840/3839
1841/3839
1842/3839
1843/3839
1844/3839
1845/3839
1846/3839
1847/3839
1848/3839
1849/3839
1850/3839
1851/3839
1852/3839
1853/3839
1854/3839
1855/3839
1856/3839
1857/3839
1858/3839
1859/3839
1860/3839
1861/3839
1862/3839
1863/3839
1864/3839
1865/3839
1866/3839
1867/3839
1868/3839
1869/3839
1870/3839
1871/3839
1872/3839
1873/3839
1874/3839
1875/3839
1876/3839
1877/3839
1878/3839
1879/3839
1880/3839
1881/3839
1882/3839
1883/3839
1884/3839
1885/3839
1886/3839
1887/3839
1888/3839
1889/3839
1890/3839
1891/3839
1892/3839
1893/3839
1894/3839
1895/3839
1896/3839
1897/3839
1898/3839
1899/3839
1900/3839
1901/3839
1902/3839
1903/3839
1904/3839
1905/3839
1906/3839
1907/3839
1908/3839
1909/3839
1910/3839
1911/3839
1912/3839
1913/3839
1914/3839
1915/3839
1916/3839
1917/3839
1918/3839
1919/3839
1920/3839
1921/3839
1922/3839
1923/3839
1924/3839
1925/3839
1926/3839
1927/3839
1928/3839
1929/3839
1930/3839
1931/3839
1932/3839
1933/3839
1934/3839
1935/3839
1936/3839
1937/3839
1938/3839
1939/3839
1940/3839
1941/3839
1942/3839
1943/3839
1944/3839
1945/3839
1946/3839
1947/3839
1948/3839
1949/3839
1950/3839
1951/3839
1952/3839
1953/3839
1954/3839
1955/3839
1956/3839
1957/3839
1958/3839
1959/3839
1960/3839
1961/3839
1962/3839
1963/3839
1964/3839
1965/3839
1966/3839
1967/3839
1968/3839

2025-05-20 07:58:54,997 - openai._base_client - INFO - Retrying request to /chat/completions in 0.414620 seconds

1969/3839
1970/3839
1971/3839
1972/3839
1973/3839
1974/3839
1975/3839
1976/3839
1977/3839
1978/3839
1979/3839
1980/3839
1981/3839
1982/3839
1983/3839
1984/3839
1985/3839
1986/3839
1987/3839
1988/3839
1989/3839
1990/3839
1991/3839
1992/3839
1993/3839
1994/3839
1995/3839
1996/3839
1997/3839
1998/3839
1999/3839
2000/3839
2001/3839
2002/3839
2003/3839
2004/3839
2005/3839
2006/3839
2007/3839
2008/3839
2009/3839
2010/3839
2011/3839
2012/3839
2013/3839
2014/3839
2015/3839
2016/3839
2017/3839
2018/3839
2019/3839
2020/3839
2021/3839
2022/3839
2023/3839
2024/3839
2025/3839
2026/3839
2027/3839
2028/3839
2029/3839
2030/3839
2031/3839
2032/3839
2033/3839
2034/3839
2035/3839
2036/3839
2037/3839
2038/3839
2039/3839
2040/3839
2041/3839
2042/3839
2043/3839
2044/3839
2045/3839
2046/3839
2047/3839
2048/3839
2049/3839
2050/3839
2051/3839
2052/3839
2053/3839
2054/3839
2055/3839
2056/3839
2057/3839
2058/3839
2059/3839
2060/3839
2061/3839
2062/3839
2063/3839
2064/3839
2065/3839
2066/3839
2067/3839
2068/3839
2069/3839
2070/3839
2071/3839
2072/3839
2073/3839
2074/3839
2075/3839
2076/3839
2077/3839
2078/3839
2079/3839
2080/3839
2081/3839
2082/3839
2083/3839
2084/3839
2085/3839
2086/3839
2087/3839
2088/3839
2089/3839
2090/3839
2091/3839
2092/3839
2093/3839
2094/3839
2095/3839
2096/3839
2097/3839
2098/3839
2099/3839
2100/3839
2101/3839
2102/3839
2103/3839
2104/3839
2105/3839
2106/3839
2107/3839
2108/3839
2109/3839
2110/3839
2111/3839
2112/3839
2113/3839
2114/3839
2115/3839
2116/3839
2117/3839
2118/3839
2119/3839
2120/3839
2121/3839
2122/3839
2123/3839
2124/3839
2125/3839
2126/3839
2127/3839
2128/3839
2129/3839
2130/3839
2131/3839
2132/3839
2133/3839
2134/3839
2135/3839
2136/3839
2137/3839
2138/3839
2139/3839
2140/3839
2141/3839
2142/3839
2143/3839
2144/3839
2145/3839
2146/3839
2147/3839
2148/3839
2149/3839
2150/3839
2151/3839
2152/3839
2153/3839
2154/3839
2155/3839
2156/3839
2157/3839
2158/3839
2159/3839
2160/3839
2161/3839
2162/3839
2163/3839
2164/3839
2165/3839
2166/3839
2167/3839
2168/3839
2169/3839
2170/3839
2171/3839
2172/3839
2173/3839
2174/3839
2175/3839
2176/3839
2177/3839
2178/3839
2179/3839
2180/3839
2181/3839
2182/3839
2183/3839
2184/3839
2185/3839
2186/3839
2187/3839
2188/3839
2189/3839
2190/3839
2191/3839
2192/3839
2193/3839
2194/3839
2195/3839
2196/3839
2197/3839
2198/3839
2199/3839
2200/3839
2201/3839
2202/3839
2203/3839
2204/3839
2205/3839
2206/3839
2207/3839
2208/3839
2209/3839
2210/3839
2211/3839
2212/3839
2213/3839
2214/3839
2215/3839
2216/3839
2217/3839
2218/3839
2219/3839
2220/3839
2221/3839
2222/3839
2223/3839
2224/3839
2225/3839
2226/3839
2227/3839
2228/3839
2229/3839
2230/3839
2231/3839
2232/3839
2233/3839
2234/3839
2235/3839
2236/3839
2237/3839
2238/3839
2239/3839
2240/3839
2241/3839
2242/3839
2243/3839
2244/3839
2245/3839
2246/3839
2247/3839
2248/3839
2249/3839
2250/3839
2251/3839
2252/3839
2253/3839
2254/3839
2255/3839
2256/3839
2257/3839
2258/3839
2259/3839
2260/3839
2261/3839
2262/3839
2263/3839
2264/3839
2265/3839
2266/3839
2267/3839
2268/3839
2269/3839
2270/3839
2271/3839
2272/3839
2273/3839
2274/3839
2275/3839
2276/3839
2277/3839
2278/3839
2279/3839
2280/3839
2281/3839
2282/3839
2283/3839
2284/3839
2285/3839
2286/3839
2287/3839
2288/3839
2289/3839
2290/3839
2291/3839
2292/3839
2293/3839
2294/3839
2295/3839
2296/3839
2297/3839
2298/3839
2299/3839
2300/3839
2301/3839
2302/3839
2303/3839
2304/3839
2305/3839
2306/3839
2307/3839
2308/3839
2309/3839
2310/3839
2311/3839
2312/3839
2313/3839
2314/3839
2315/3839
2316/3839
2317/3839
2318/3839
2319/3839
2320/3839
2321/3839
2322/3839
2323/3839
2324/3839
2325/3839
2326/3839
2327/3839
2328/3839
2329/3839
2330/3839
2331/3839
2332/3839
2333/3839
2334/3839
2335/3839
2336/3839
2337/3839
2338/3839
2339/3839
2340/3839
2341/3839
2342/3839
2343/3839
2344/3839
2345/3839
2346/3839
2347/3839
2348/3839
2349/3839
2350/3839
2351/3839
2352/3839
2353/3839
2354/3839
2355/3839
2356/3839
2357/3839
2358/3839
2359/3839
2360/3839
2361/3839
2362/3839
2363/3839
2364/3839
2365/3839
2366/3839
2367/3839
2368/3839
2369/3839
2370/3839
2371/3839
2372/3839
2373/3839
2374/3839
2375/3839
2376/3839
2377/3839
2378/3839
2379/3839
2380/3839
2381/3839
2382/3839
2383/3839
2384/3839
2385/3839
2386/3839
2387/3839
2388/3839
2389/3839
2390/3839
2391/3839
2392/3839
2393/3839
2394/3839
2395/3839
2396/3839
2397/3839
2398/3839
2399/3839
2400/3839
2401/3839
2402/3839
2403/3839
2404/3839
2405/3839
2406/3839
2407/3839
2408/3839
2409/3839
2410/3839
2411/3839
2412/3839
2413/3839
2414/3839
2415/3839
2416/3839
2417/3839
2418/3839
2419/3839
2420/3839
2421/3839
2422/3839
2423/3839
2424/3839
2425/3839
2426/3839
2427/3839
2428/3839
2429/3839
2430/3839
2431/3839
2432/3839
2433/3839
2434/3839
2435/3839
2436/3839
2437/3839
2438/3839
2439/3839
2440/3839
2441/3839
2442/3839
2443/3839
2444/3839
2445/3839
2446/3839
2447/3839
2448/3839
2449/3839
2450/3839
2451/3839
2452/3839
2453/3839
2454/3839
2455/3839
2456/3839
2457/3839
2458/3839
2459/3839
2460/3839
2461/3839
2462/3839
2463/3839
2464/3839
2465/3839
2466/3839
2467/3839
2468/3839
2469/3839
2470/3839
2471/3839
2472/3839
2473/3839
2474/3839
2475/3839
2476/3839
2477/3839
2478/3839
2479/3839
2480/3839
2481/3839
2482/3839
2483/3839
2484/3839
2485/3839
2486/3839
2487/3839
2488/3839
2489/3839
2490/3839
2491/3839
2492/3839
2493/3839
2494/3839
2495/3839
2496/3839
2497/3839
2498/3839
2499/3839
2500/3839
2501/3839
2502/3839
2503/3839
2504/3839
2505/3839
2506/3839
2507/3839
2508/3839
2509/3839
2510/3839
2511/3839
2512/3839
2513/3839
2514/3839
2515/3839
2516/3839
2517/3839
2518/3839
2519/3839
2520/3839
2521/3839
2522/3839
2523/3839
2524/3839
2525/3839
2526/3839
2527/3839
2528/3839
2529/3839
2530/3839
2531/3839
2532/3839
2533/3839
2534/3839
2535/3839
2536/3839
2537/3839
2538/3839
2539/3839
2540/3839
2541/3839
2542/3839
2543/3839
2544/3839
2545/3839
2546/3839
2547/3839
2548/3839
2549/3839
2550/3839
2551/3839
2552/3839
2553/3839
2554/3839
2555/3839
2556/3839
2557/3839
2558/3839
2559/3839
2560/3839
2561/3839
2562/3839
2563/3839
2564/3839
2565/3839
2566/3839
2567/3839
2568/3839
2569/3839
2570/3839
2571/3839
2572/3839
2573/3839
2574/3839
2575/3839
2576/3839
2577/3839
2578/3839
2579/3839
2580/3839
2581/3839
2582/3839
2583/3839
2584/3839
2585/3839
2586/3839
2587/3839
2588/3839
2589/3839
2590/3839
2591/3839
2592/3839
2593/3839
2594/3839
2595/3839
2596/3839
2597/3839
2598/3839
2599/3839
2600/3839
2601/3839
2602/3839
2603/3839
2604/3839
2605/3839
2606/3839
2607/3839
2608/3839
2609/3839
2610/3839
2611/3839
2612/3839
2613/3839
2614/3839
2615/3839
2616/3839
2617/3839
2618/3839
2619/3839
2620/3839
2621/3839
2622/3839
2623/3839
2624/3839
2625/3839
2626/3839
2627/3839
2628/3839
2629/3839
2630/3839
2631/3839
2632/3839
2633/3839
2634/3839
2635/3839
2636/3839
2637/3839
2638/3839
2639/3839
2640/3839
2641/3839
2642/3839
2643/3839
2644/3839
2645/3839
2646/3839
2647/3839
2648/3839
2649/3839
2650/3839
2651/3839
2652/3839
2653/3839
2654/3839
2655/3839
2656/3839
2657/3839
2658/3839
2659/3839
2660/3839
2661/3839
2662/3839
2663/3839
2664/3839
2665/3839
2666/3839
2667/3839
2668/3839
2669/3839
2670/3839
2671/3839
2672/3839
2673/3839
2674/3839
2675/3839
2676/3839
2677/3839
2678/3839
2679/3839
2680/3839
2681/3839
2682/3839
2683/3839
2684/3839
2685/3839
2686/3839
2687/3839
2688/3839
2689/3839
2690/3839
2691/3839
2692/3839
2693/3839
2694/3839
2695/3839
2696/3839
2697/3839
2698/3839
2699/3839
2700/3839
2701/3839
2702/3839
2703/3839
2704/3839
2705/3839
2706/3839
2707/3839
2708/3839
2709/3839
2710/3839
2711/3839
2712/3839
2713/3839
2714/3839
2715/3839
2716/3839
2717/3839
2718/3839
2719/3839
2720/3839
2721/3839
2722/3839
2723/3839
2724/3839
2725/3839
2726/3839
2727/3839
2728/3839
2729/3839
2730/3839
2731/3839
2732/3839
2733/3839
2734/3839
2735/3839
2736/3839
2737/3839
2738/3839
2739/3839
2740/3839
2741/3839
2742/3839
2743/3839
2744/3839
2745/3839
2746/3839
2747/3839
2748/3839
2749/3839
2750/3839
2751/3839
2752/3839
2753/3839
2754/3839
2755/3839
2756/3839
2757/3839
2758/3839
2759/3839
2760/3839
2761/3839
2762/3839
2763/3839
2764/3839
2765/3839
2766/3839
2767/3839
2768/3839
2769/3839
2770/3839
2771/3839
2772/3839
2773/3839
2774/3839
2775/3839
2776/3839
2777/3839
2778/3839
2779/3839
2780/3839
2781/3839
2782/3839
2783/3839
2784/3839
2785/3839
2786/3839
2787/3839
2788/3839
2789/3839
2790/3839
2791/3839
2792/3839
2793/3839
2794/3839
2795/3839
2796/3839
2797/3839
2798/3839
2799/3839
2800/3839
2801/3839
2802/3839
2803/3839
2804/3839
2805/3839
2806/3839
2807/3839
2808/3839
2809/3839
2810/3839
2811/3839
2812/3839
2813/3839
2814/3839
2815/3839
2816/3839
2817/3839
2818/3839
2819/3839
2820/3839
2821/3839
2822/3839
2823/3839
2824/3839
2825/3839
2826/3839
2827/3839
2828/3839
2829/3839
2830/3839
2831/3839
2832/3839
2833/3839
2834/3839
2835/3839
2836/3839
2837/3839
2838/3839
2839/3839
2840/3839
2841/3839
2842/3839
2843/3839
2844/3839
2845/3839
2846/3839
2847/3839
2848/3839
2849/3839
2850/3839
2851/3839
2852/3839
2853/3839
2854/3839
2855/3839
2856/3839
2857/3839
2858/3839
2859/3839
2860/3839
2861/3839
2862/3839
2863/3839
2864/3839
2865/3839
2866/3839
2867/3839
2868/3839
2869/3839
2870/3839
2871/3839
2872/3839
2873/3839
2874/3839
2875/3839
2876/3839
2877/3839
2878/3839
2879/3839
2880/3839
2881/3839
2882/3839
2883/3839
2884/3839
2885/3839
2886/3839
2887/3839
2888/3839
2889/3839
2890/3839
2891/3839
2892/3839
2893/3839
2894/3839
2895/3839
2896/3839
2897/3839
2898/3839
2899/3839
2900/3839
2901/3839
2902/3839
2903/3839
2904/3839
2905/3839
2906/3839
2907/3839
2908/3839
2909/3839
2910/3839
2911/3839
2912/3839
2913/3839
2914/3839
2915/3839
2916/3839
2917/3839
2918/3839
2919/3839
2920/3839
2921/3839
2922/3839
2923/3839
2924/3839
2925/3839
2926/3839
2927/3839
2928/3839
2929/3839
2930/3839
2931/3839
2932/3839
2933/3839
2934/3839
2935/3839
2936/3839
2937/3839
2938/3839
2939/3839
2940/3839
2941/3839
2942/3839
2943/3839
2944/3839
2945/3839
2946/3839
2947/3839
2948/3839
2949/3839
2950/3839
2951/3839
2952/3839
2953/3839
2954/3839
2955/3839
2956/3839
2957/3839
2958/3839
2959/3839
2960/3839
2961/3839
2962/3839
2963/3839
2964/3839
2965/3839
2966/3839
2967/3839
2968/3839
2969/3839
2970/3839
2971/3839
2972/3839
2973/3839
2974/3839
2975/3839
2976/3839
2977/3839
2978/3839
2979/3839
2980/3839
2981/3839
2982/3839
2983/3839
2984/3839
2985/3839
2986/3839
2987/3839
2988/3839
2989/3839
2990/3839
2991/3839
2992/3839
2993/3839
2994/3839
2995/3839
2996/3839
2997/3839
2998/3839
2999/3839
3000/3839
3001/3839
3002/3839
3003/3839
3004/3839
3005/3839
3006/3839
3007/3839
3008/3839
3009/3839
3010/3839
3011/3839
3012/3839
3013/3839
3014/3839
3015/3839
3016/3839
3017/3839
3018/3839
3019/3839
3020/3839
3021/3839
3022/3839
3023/3839
3024/3839
3025/3839
3026/3839
3027/3839
3028/3839
3029/3839
3030/3839
3031/3839
3032/3839
3033/3839
3034/3839
3035/3839
3036/3839
3037/3839
3038/3839
3039/3839
3040/3839
3041/3839
3042/3839
3043/3839
3044/3839
3045/3839
3046/3839
3047/3839
3048/3839
3049/3839
3050/3839
3051/3839
3052/3839
3053/3839
3054/3839
3055/3839
3056/3839
3057/3839
3058/3839
3059/3839
3060/3839
3061/3839
3062/3839
3063/3839
3064/3839
3065/3839
3066/3839
3067/3839
3068/3839
3069/3839
3070/3839
3071/3839
3072/3839
3073/3839
3074/3839
3075/3839
3076/3839
3077/3839
3078/3839
3079/3839
3080/3839
3081/3839
3082/3839
3083/3839
3084/3839
3085/3839
3086/3839
3087/3839
3088/3839
3089/3839
3090/3839
3091/3839
3092/3839
3093/3839
3094/3839
3095/3839
3096/3839
3097/3839
3098/3839
3099/3839
3100/3839
3101/3839
3102/3839
3103/3839
3104/3839
3105/3839
3106/3839
3107/3839
3108/3839
3109/3839
3110/3839
3111/3839
3112/3839
3113/3839
3114/3839
3115/3839
3116/3839
3117/3839
3118/3839
3119/3839
3120/3839
3121/3839
3122/3839
3123/3839
3124/3839
3125/3839
3126/3839
3127/3839
3128/3839
3129/3839
3130/3839
3131/3839
3132/3839
3133/3839
3134/3839
3135/3839
3136/3839
3137/3839
3138/3839
3139/3839
3140/3839
3141/3839
3142/3839
3143/3839
3144/3839
3145/3839
3146/3839
3147/3839
3148/3839
3149/3839
3150/3839
3151/3839
3152/3839
3153/3839
3154/3839
3155/3839
3156/3839
3157/3839
3158/3839
3159/3839
3160/3839
3161/3839
3162/3839
3163/3839
3164/3839
3165/3839
3166/3839
3167/3839
3168/3839
3169/3839
3170/3839
3171/3839
3172/3839
3173/3839
3174/3839
3175/3839
3176/3839
3177/3839
3178/3839
3179/3839
3180/3839
3181/3839
3182/3839
3183/3839
3184/3839
3185/3839
3186/3839
3187/3839
3188/3839
3189/3839
3190/3839
3191/3839
3192/3839
3193/3839
3194/3839
3195/3839
3196/3839
3197/3839
3198/3839
3199/3839
3200/3839
3201/3839
3202/3839
3203/3839
3204/3839
3205/3839
3206/3839
3207/3839
3208/3839
3209/3839
3210/3839
3211/3839
3212/3839
3213/3839
3214/3839
3215/3839
3216/3839
3217/3839
3218/3839
3219/3839
3220/3839
3221/3839
3222/3839
3223/3839
3224/3839
3225/3839
3226/3839
3227/3839
3228/3839
3229/3839
3230/3839
3231/3839
3232/3839
3233/3839
3234/3839
3235/3839
3236/3839
3237/3839
3238/3839
3239/3839
3240/3839
3241/3839
3242/3839
3243/3839
3244/3839
3245/3839
3246/3839
3247/3839
3248/3839
3249/3839
3250/3839
3251/3839
3252/3839
3253/3839
3254/3839
3255/3839
3256/3839
3257/3839
3258/3839
3259/3839
3260/3839
3261/3839
3262/3839
3263/3839
3264/3839
3265/3839
3266/3839
3267/3839
3268/3839
3269/3839
3270/3839
3271/3839
3272/3839
3273/3839
3274/3839
3275/3839
3276/3839
3277/3839
3278/3839
3279/3839
3280/3839
3281/3839
3282/3839
3283/3839
3284/3839
3285/3839
3286/3839
3287/3839
3288/3839
3289/3839
3290/3839
3291/3839
3292/3839
3293/3839
3294/3839
3295/3839
3296/3839
3297/3839
3298/3839
3299/3839
3300/3839
3301/3839
3302/3839
3303/3839
3304/3839
3305/3839
3306/3839
3307/3839
3308/3839
3309/3839
3310/3839
3311/3839
3312/3839
3313/3839
3314/3839
3315/3839
3316/3839
3317/3839
3318/3839
3319/3839
3320/3839
3321/3839
3322/3839
3323/3839
3324/3839
3325/3839
3326/3839
3327/3839
3328/3839
3329/3839
3330/3839
3331/3839
3332/3839
3333/3839
3334/3839
3335/3839
3336/3839
3337/3839
3338/3839
3339/3839
3340/3839
3341/3839
3342/3839
3343/3839
3344/3839
3345/3839
3346/3839
3347/3839
3348/3839
3349/3839
3350/3839
3351/3839
3352/3839
3353/3839
3354/3839
3355/3839
3356/3839
3357/3839
3358/3839
3359/3839
3360/3839
3361/3839
3362/3839
3363/3839
3364/3839
3365/3839
3366/3839
3367/3839
3368/3839
3369/3839
3370/3839
3371/3839
3372/3839
3373/3839
3374/3839
3375/3839
3376/3839
3377/3839
3378/3839
3379/3839
3380/3839
3381/3839
3382/3839
3383/3839
3384/3839
3385/3839
3386/3839
3387/3839
3388/3839
3389/3839
3390/3839
3391/3839
3392/3839
3393/3839
3394/3839
3395/3839
3396/3839
3397/3839
3398/3839
3399/3839
3400/3839
3401/3839
3402/3839
3403/3839
3404/3839
3405/3839
3406/3839
3407/3839
3408/3839
3409/3839
3410/3839
3411/3839
3412/3839
3413/3839
3414/3839
3415/3839
3416/3839
3417/3839
3418/3839
3419/3839
3420/3839
3421/3839
3422/3839
3423/3839
3424/3839
3425/3839
3426/3839
3427/3839
3428/3839
3429/3839
3430/3839
3431/3839
3432/3839
3433/3839
3434/3839
3435/3839
3436/3839
3437/3839
3438/3839
3439/3839
3440/3839
3441/3839
3442/3839
3443/3839
3444/3839
3445/3839
3446/3839
3447/3839
3448/3839
3449/3839
3450/3839
3451/3839
3452/3839
3453/3839
3454/3839
3455/3839
3456/3839
3457/3839
3458/3839
3459/3839
3460/3839
3461/3839
3462/3839
3463/3839
3464/3839
3465/3839
3466/3839
3467/3839
3468/3839
3469/3839
3470/3839
3471/3839
3472/3839
3473/3839
3474/3839
3475/3839
3476/3839
3477/3839
3478/3839
3479/3839
3480/3839
3481/3839
3482/3839
3483/3839
3484/3839
3485/3839
3486/3839
3487/3839
3488/3839
3489/3839
3490/3839
3491/3839
3492/3839
3493/3839
3494/3839
3495/3839
3496/3839
3497/3839
3498/3839
3499/3839
3500/3839
3501/3839
3502/3839
3503/3839
3504/3839
3505/3839
3506/3839
3507/3839
3508/3839
3509/3839
3510/3839
3511/3839
3512/3839
3513/3839
3514/3839
3515/3839
3516/3839
3517/3839
3518/3839
3519/3839
3520/3839
3521/3839
3522/3839
3523/3839
3524/3839
3525/3839
3526/3839
3527/3839
3528/3839
3529/3839
3530/3839
3531/3839
3532/3839
3533/3839
3534/3839
3535/3839
3536/3839
3537/3839
3538/3839
3539/3839
3540/3839
3541/3839
3542/3839
3543/3839
3544/3839
3545/3839
3546/3839
3547/3839
3548/3839
3549/3839
3550/3839
3551/3839
3552/3839
3553/3839
3554/3839
3555/3839
3556/3839
3557/3839
3558/3839
3559/3839
3560/3839
3561/3839
3562/3839
3563/3839
3564/3839
3565/3839
3566/3839
3567/3839
3568/3839
3569/3839
3570/3839
3571/3839
3572/3839
3573/3839
3574/3839
3575/3839
3576/3839
3577/3839
3578/3839
3579/3839
3580/3839
3581/3839
3582/3839
3583/3839

LengthFinishReasonError: Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=59, prompt_tokens=742, total_tokens=801, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0))

In [15]:
result_df = pd.DataFrame(result_datas)

In [19]:
result_df[result_df.effect_size_type.str.contains("effect size")]

,id,result,intervention_variable,outcome_variable,effect_size,effect_size_number,effect_size_type,uncertainty,p_value,effect_sign
8,https://openalex.org/W1951736428,Linguistic comprehension instruction showed sm...,Linguistic comprehension instruction,generalized linguistic comprehension outcomes ...,small positive immediate effects on generalize...,0.200,standardized effect size (small to moderate),N/A,N/A,POSITIVE
9,https://openalex.org/W1951736428,Linguistic comprehension instruction had negli...,Linguistic comprehension instruction,generalized reading comprehension outcomes,negligible immediate effects,0.000,effect size (not numerically specified),few studies reporting follow-up assessments wi...,N/A,NONE
129,https://openalex.org/W2050802668,A 24-session caregiver-mediated joint attentio...,24-session caregiver-mediated joint attention ...,"joint engagement, responsiveness to joint atte...",medium to large effect sizes,0.000,effect size,N/A,significant improvements,POSITIVE
207,https://openalex.org/W2277832614,Level 4 SSTP was strongly supported as an effe...,Level 4 Stepping Stones Triple P (SSTP),child and parent outcomes in families of child...,Strong support as an effective intervention,0.700,effect size (d) for parenting style as an exam...,N/A,N/A,POSITIVE
233,https://openalex.org/W1578640603,Group social skills interventions (GSSIs) for ...,Group social skills interventions (GSSIs),social responsiveness as measured by the paren...,Large positive effect sizes,0.000,effect size,N/A,N/A,POSITIVE
234,https://openalex.org/W1578640603,GSSIs that included parent-groups and had grea...,GSSIs that include parent-groups and have grea...,social responsiveness (measured by SRS),larger effect sizes,0.000,effect size,N/A,N/A,POSITIVE
463,https://openalex.org/W1894556437,A comprehensive psychosocial intervention targ...,comprehensive psychosocial intervention target...,five of seven primary outcome measures in chil...,Standardized effect size estimates were predom...,0.000,standardized effect size,N/A,significant treatment effects,POSITIVE
464,https://openalex.org/W1894556437,The intervention's response-cost program effec...,response-cost program,problem behaviors and skills acquisition,Standardized effect size estimates were predom...,0.000,standardized effect size,N/A,N/A,POSITIVE
492,https://openalex.org/W2969935787,A 6-session family-based HIV prevention interv...,6-session family-based HIV prevention interven...,parents' reports of sex communication outcomes...,medium to large effects at postintervention an...,0.500,effect size (Cohen's d or similar),N/A,N/A,POSITIVE
493,https://openalex.org/W2969935787,Youth reports showed small to medium effects f...,family-based HIV prevention intervention targe...,communication variables (content and quality),small to medium effects,0.300,effect size (Cohen's d or similar),lasting through the 6-month follow-up period,N/A,POSITIVE
654,https://openalex.org/W1977832073,A parent-focused early intervention programme ...,parent-focused early intervention programme,parents' and children's communicative interact...,Large-effect sizes were observed,0.000,effect size (unspecified),N/A,significantly,POSITIVE
701,https://openalex.org/W3129050467,An online parent intervention using LENA-based...,Online parent intervention using LENA-based au...,Talk and interaction among parents with below ...,Significant increases in talk and interaction ...,0.000,Significant increase (exact numerical effect s...,N/A,N/A,POSITIVE
746,https://openalex.org/W48489379,The Reminiscing and Emotion Training (RET) int...,Reminiscing and Emotion Training (RET) interve...,mothers' elaboration and sensitive guidance du...,medium to large effect sizes,0.500,effect size (medium to large),N/A,significantly better,POSITIVE
1009,https://openalex.org/W3216926178,Psychosocial interventions such as support gro...,Psychosocial interventions such as support gro...,caregiver burden,0.09-0.23,0.160,effect size,N/A,N/A,NEGATIVE
1010,https://openalex.org/W3216926178,Pharmacologic interventions including antichol...,Pharmacologic interventions including antichol...,caregiver burden,0.18-0.27,0.225,effect size,range 0.18-0.27,N/A,NEGATIVE
1011,https://openalex.org/W3216926178,Many interventions improved caregiver burden–a...,Psychosocial and pharmacological interventions,Caregiver burden–associated symptoms like mood...,Psychosocial interventions effect size 0.09-0....,0.090,Standardized effect size (range),Effect size ranges reported (0.09-0.23 for psy...,N/A,POSITIVE
1034,https://openalex.org/W2287650648,The Reach Up early childhood parenting program...,Reach Up early childhood parenting program,child cognitive development,0.49,0.490,effect size (standardized mean difference),95% confidence interval [CI] 0.32 to 0.66,N/A,POSITIVE
1037,https://openalex.org/W2801259186,PTA showed non-significant but favorable effec...,Positive Thoughts and Actions (PTA) prevention...,"coping, cognitive style, and parent-child comm...",non-significant but favorable effect sizes,0.000,effect size (unspecified),not statistically significant,not significant,POSITIVE
1056,https://openalex.org/W2001753660,A 20-week storybook-based intervention signifi...,20-week storybook-based intervention,preliteracy skills in 3- to 6-year-olds,effect sizes = .21–.27,0.210,Cohen's d (effect size),range from .21 to .27,significant,POSITIVE
1248,https://openalex.org/W2042011789,Conjoint behavioral consultation (CBC) interve...,Conjoint behavioral consultation (CBC) interve...,Behavioral change and goal attainment,generally high effect sizes,0.000,effect size,N/A,N/A,POSITIVE
1249,https://openalex.org/W2042011789,Participants including teachers and family mem...,Conjoint behavioral consultation (CBC) model,"Acceptability, satisfaction, and perceived eff...",Generally high effect sizes regardless of dive...,0.000,effect size (unspecified),N/A,N/A,POSITIVE
1471,https://openalex.org/W2090857190,The intervention had a moderate positive effec...,SuperSpeech online group intervention targetin...,children's perception of being happy talking i...,moderate effect,0.500,effect size (moderate),N/A,N/A,POSITIVE
1578,https://openalex.org/W2274804584,The degree of cultural adaptation was proporti...,degree of cultural adaptation,efficacy of the intervention,Culturally adapted interventions were more eff...,-0.230,Hedges' g (effect size for total symptom sever...,95% confidence interval (CI) −0.36 to −0.09,N/A,NEGATIVE
1625,https://openalex.org/W2136593335,TEACCH-based group social skills training for ...,TEACCH-based group social skills training for ...,children's adaptive behaviors and social recip...,"moderate effect sizes (SDQ, 0.71; PSI, 0.58; B...",0.710,Cohen's d (effect size),N/A,N/A,POSITIVE
1817,https://openalex.org/W2157236609,Participation in the relationships component o...,Participation in the relationships component o...,Frequency of parental sexual communication and...,Increased frequency and number after accountin...,42.700,Percentage participation and increased frequen...,N/A,N/A,POSITIVE
1822,https://openalex.org/W4200529648,The Ms. Now! parent-based intervention increas...,Ms. Now! parent-based intervention,"parent–child relationship quality, parental mo...",positive intervention effects approaching medi...,0.500,effect size (medium to large),approaching medium to large effect sizes,N/A,POSITIVE
1856,https://openalex.org/W2285668379,Direct Instruction curricula significantly imp...,Direct Instruction curricula,"academic outcomes in reading, math, language, ...",positive and statistically significant effects...,0.500,standardized mean difference (effect size),all effects statistically significant except a...,statistically significant,POSITIVE
1857,https://openalex.org/W2285668379,Increased exposure to Direct Instruction progr...,Increased exposure to Direct Instruction programs,academic effects,moderate to large and educationally significant,0.500,effect size (standardized mean difference),all were statistically significant,statistically significant,POSITIVE
2021,https://openalex.org/W2120485993,Individually delivered social competence train...,Individually delivered social competence train...,reducing aggressive behavior and improving psy...,Moderate treatment effects for THAV compared t...,0.500,treatment effect size (moderate),"Outcome measures were rated by parents, teache...",N/A,POSITIVE
2023,https://openalex.org/W2120485993,Cognitive behavioral skill training improved s...,Cognitive behavioral skill training,"social problem-solving skills, impulsivity, an...",Moderate treatment effects for social competen...,0.500,treatment effect size (moderate),Not specified,Not specified,POSITIVE
2122,https://openalex.org/W2937793371,The gratitude-themed intervention improved all...,gratitude-themed intervention,"family communication, family well-being, and s...",small effect sizes,0.000,effect size,sustained up to 12 weeks,N/A,POSITIVE
2193,https://openalex.org/W2004143323,The RELAX intervention targeting emotion dysre...,RELAX intervention targeting emotion dysregula...,adolescent emotion dysregulation and family co...,large improvements; d = 1.10 and 1.23 for emot...,1.770,Cohen's d (effect size),N/A,N/A,POSITIVE
2194,https://openalex.org/W2004143323,Parents showed large increases in supportive r...,RELAX intervention,supportive reactions during conflict discussio...,d = 1.04 for supportive reactions; d = 0.82 fo...,1.040,Cohen's d (effect size),N/A,N/A,POSITIVE
2251,https://openalex.org/W2071684906,LENA Start™ parent-training program increased ...,LENA Start™ parent-training program,child vocalizations and conversational turns,small to medium-sized effects favoring LENA St...,0.300,effect size (small to medium),significant for child vocalizations and conver...,significant for child vocalizations and conver...,POSITIVE
2940,https://openalex.org/W3038868547,The Incredible Years Parent–Toddler Programme ...,The Incredible Years Parent–Toddler Programme ...,child-led language interactions and encouragin...,child-led language interactions significantly ...,0.470,effect size (ES),95% confidence intervals (CI) = −2.59 to −0.29...,P = 0.015 for child-led language; P = 0.03 for...,POSITIVE
3059,https://openalex.org/W3093071443,Interventions aimed at reducing sedentary beha...,Interventions aimed at reducing sedentary beha...,Sedentary time,small but significant reduction in sedentary t...,-0.290,effect size (standardized mean difference),95% CI -0.35 to -0.22,N/A,NEGATIVE
3083,https://openalex.org/W2057739347,Parent-Child Interaction Therapy (PCIT) decrea...,Parent-Child Interaction Therapy (PCIT),disruptive behavior in young children with Aut...,medium to large effect sizes across measured d...,0.500,effect size (medium to large),N/A,significantly decreased,NEGATIVE
3084,https://openalex.org/W2057739347,PCIT increased positive parental following ski...,Parent-Child Interaction Therapy (PCIT),positive parental following skills and negativ...,medium to large effect sizes across measured d...,0.500,effect size (medium to large),N/A,significantly decreased (p-value not specified),POSITIVE
3085,https://openalex.org/W2057739347,Parents reported increased child functional co...,Parent-Child Interaction Therapy (PCIT),child functional communication and prosocial b...,medium to large effect sizes across measured d...,0.500,effect size (medium to large),N/A,significantly decreased disruptive behavior (p...,POSITIVE
3132,https://openalex.org/W2021186261,The parent-mediated early autism intervention ...,Parent-mediated early autism intervention,ADOS algorithm scores for children with 'few t...,medium significant improvement,0.500,effect size (medium),significant,significant,POSITIVE
3147,https://openalex.org/W1966456570,A nurse-delivered counselling intervention inv...,Nurse-delivered counselling intervention invol...,"Parental disclosure distress, self-efficacy, a...",At least one result for each outcome indicatin...,0.000,large effect size (unspecified),Small sample size; statistically significant r...,Statistically significant (exact p-values not ...,NEGATIVE for disclosure distress (reduced dist...
3148,https://openalex.org/W1966456570,The intervention led to statistically signific...,Nurse-delivered counselling intervention invol...,Parental HIV disclosure outcomes including sel...,Some results showing large effect sizes,0.000,large effect size (unspecified),Statistically significant results despite smal...,Statistically significant (exact values not pr...,POSITIVE
3164,https://openalex.org/W2101692132,Interventions focusing on the verbal processin...,Interventions focusing on the verbal processin...,psychological symptomatology in refugee and as...,effect sizes ranging from 0.31 to 0.93,0.310,effect size (range),N/A,significant changes,NEGATIVE
3165,https://openalex.org/W2101692132,Creative art technique interventions also repo...,Creative art technique interventions,symptomatology among refugee and asylum-seekin...,effect sizes ranged from 0.31 to 0.93 (mainly ...,0.310,effect size (range),N/A,significant changes reported (p-value not spec...,POSITIVE

In [17]:
result_df.to_csv("pet_scan_3_results_2.csv", index=False)