In [39]:
import pandas as pd
from discovery_utils.utils.llm import batch_check

import pandas as pd
import os


data_df = (
    pd.read_csv('afs_open_alex_scan.csv')
    .query("publication_year >= 2000")
    .assign(text = lambda df: df['title'] + ' ' + df['abstract'])
)
len(data_df)

7853

In [82]:
from ast import literal_eval

def extract_author_countries(authorships):
    try:
        # Convert the string representation of the list to an actual list
        authors = literal_eval(authorships)
        countries = []
        for author in authors:
            for institution in author.get('institutions', []):
                if 'country_code' in institution:
                    countries.append(institution['country_code'])
        # remove null values
        countries = [country for country in countries if country is not None]
        return sorted(list(set(countries)))
    except (ValueError, SyntaxError):
        # Handle the case where the string cannot be evaluated
        return []

In [56]:
_data_df = data_df

In [57]:
ids = _data_df.id.tolist()
text = data_df.text.tolist()
test_data = dict(zip(ids, text))

In [58]:
len(test_data)

7852

In [59]:
system_message = (
    "Extract structured information about a measurement or evaluation tool that is used to assess various developmental outcomes "
    "for children under 5 or outcomes for their parents. The tool should be relevant to developmental, behavioural, or well-being outcomes "
    "such as children language development, cognitive development, social-emotional skills, physical and mental health, or "
    "parental outcomes such as confidence, skills, behaviours, knowledge, self-efficacy, and well-being. "
    "The tool could be a questionnaire, structured observation, digital tool or any other form of measurement. "
    "If the input text does not describe such a tool or if input text doesn't useful information (e.g. it's just a list of references)"
    "indicate it is not relevant. When available, provide detailed attributes "
    "such as age suitability, outcome domains, form of measurement, population validated on, and any evidence of effectiveness."
    "Unless requested otherwise, adhere as precisely as possible to the language and text that is used in the provided text document."
    "If the requested information is not described, return N/A. DO NOT make up any false information or false inferences."
)

fields = [
    {"name": "is_relevant", "type": "str", "description": "One-word answer: 'yes' if the text is about a tool for measuring relevant outcomes for children under 5 or their parents, otherwise 'no'."},
    {"name": "is_relevant_reason", "type": "str", "description": "Short explanation (one sentence, 20 words) of why the text is relevant or not."},
    {"name": "tool_type", "type": "str", "description": "Who is the tool used for - one of the following 'Children', 'Parents', 'Both', or 'Other'."},
    {"name": "tool_name", "type": "str", "description": "The name of the measurement or evaluation tool."},
    {"name": "age_range", "type": "str", "description": "The age group the tool is suitable for, as described in the text e.g., '0-5 years', 'infants', 'toddlers'."},
    {"name": "age_range_numerical", "type": "str", "description": "Infer the probable age range in numerical format (e.g., '0-5', '0-2', '3-5')."},
    {"name": "child_outcomes", "type": "list[str]", "description": "List of child-related outcome domains the tool measures, such as 'language development', 'cognitive development', 'social-emotional skills', 'physical health'."},
    {"name": "child_outcomes_category", "type": "list[str]", "description": "Infer if the child-related outcomes are best categorised in one of the following: 'Physical health and development', 'Mental health', 'Social, emotional and behavioral', 'Cognitive development', 'Speech, language and communication', 'N/A'."},
    {"name": "parent_outcomes", "type": "list[str]", "description": "List of parent-related outcomes, such as 'parental confidence', 'knowledge', 'self-efficacy', 'wellbeing'."},
    {"name": "parent_outcomes_category", "type": "list[str]", "description": "Infer if the parent-related outcomes are best categorised in one of the following: 'Parental behaviours and skills', 'Parental beliefs and knowledge', 'Parental well-being and mental health', 'N/A'."},
    {"name": "population_validated", "type": "str", "description": "The population(s) or demographics the tool has been tested or validated with."},
    {"name": "measurement_format", "type": "str", "description": "The format of the tool, e.g., 'questionnaire', 'structured observation', 'parent-reported survey', 'digital app', or others"},
    {"name": "duration_minutes", "type": "int", "description": "Approximate time in minutes it takes to complete the tool, if described."},
    {"name": "evidence", "type": "list[str]", "description": "Explanation of the tools effectiveness or evidence of its impact, if described."},
    {"name": "global_vs_specific", "type": "str", "description": "'global' if the tool measures overall domains (e.g., language development broadly), 'specific' if it targets sub-domains (e.g., gestures, vocalisation), or 'both'."},
    {"name": "ease_of_use", "type": "str", "description": "A qualitative description of the tool’s usability or burden (e.g., easy, moderate, difficult)."},
    {"name": "acceptability", "type": "str", "description": "Acceptability to users (both those completing and administering the tool), if described."},
    {"name": "special_requirements", "type": "str", "description": "Any specific requirements, such as 'needs to be administered twice', 'requires training'."},
    {"name": "geography", "type": "str", "description": "Geographic relevance or validation setting, if specified (e.g., 'UK', 'low-income US settings')."},
    {"name": "country", "type": "str", "description": "Infer country name or names based on the text, if described."},
    {"name": "cost", "type": "str", "description": "Any cost-related information, such as 'free', 'paid license', or specific pricing if stated."},
    {"name": "pros", "type": "list[str]", "description": "List of strengths or advantages of the tool, as stated in the text."},
    {"name": "cons", "type": "list[str]", "description": "List of limitations, drawbacks, or reasons not to use the tool in some cases, as stated in the text."}
]

In [ ]:
processor = batch_check.LLMProcessor(
    model_name="gpt-4.1-mini",
    temperature=0,
    output_path="afs_open_alex_scan_1.jsonl",
    system_message=system_message,
    session_name="afs_open_alex_scan",
    output_fields=fields,
)

processor.run(test_data, batch_size=10, sleep_time=0.5)

2025-04-23 22:16:26,539 - root - INFO - Using OpenAI

2025-04-23 22:16:26,677 - root - INFO - Processing batch 1/736
2025-04-23 22:16:35,574 - root - INFO - Processing batch 2/736
2025-04-23 22:16:44,496 - root - INFO - Processing batch 3/736
2025-04-23 22:16:50,533 - root - INFO - Processing batch 4/736
2025-04-23 22:16:56,539 - root - INFO - Processing batch 5/736
2025-04-23 22:17:02,588 - root - INFO - Processing batch 6/736
2025-04-23 22:17:11,869 - root - INFO - Processing batch 7/736
2025-04-23 22:17:16,872 - root - INFO - Processing batch 8/736
2025-04-23 22:17:21,554 - root - INFO - Processing batch 9/736
2025-04-23 22:17:27,724 - root - INFO - Processing batch 10/736
2025-04-23 22:17:35,114 - root - INFO - Processing batch 11/736
2025-04-23 22:17:40,531 - root - INFO - Processing batch 12/736
2025-04-23 22:17:45,617 - root - INFO - Processing batch 13/736
2025-04-23 22:17:52,702 - root - INFO - Processing batch 14/736
2025-04-23 22:17:57,431 - root - INFO - Processing batch 15/736
2025-04-23 22:18:03,085 - root - INFO - Processing batch 16/736
2025-04-23 22:18:12,968 - root - INFO - Processing batch 17/736
2025-04-23 22:18:20,545 - root - INFO - Processing batch 18/736
2025-04-23 22:18:27,112 - root - INFO - Processing batch 19/736
2025-04-23 22:18:34,579 - root - INFO - Processing batch 20/736
2025-04-23 22:18:43,404 - root - INFO - Processing batch 21/736
2025-04-23 22:18:49,045 - root - INFO - Processing batch 22/736
2025-04-23 22:18:55,055 - root - INFO - Processing batch 23/736
2025-04-23 22:19:03,145 - root - INFO - Processing batch 24/736
2025-04-23 22:19:12,267 - root - INFO - Processing batch 25/736
2025-04-23 22:19:19,392 - root - INFO - Processing batch 26/736
2025-04-23 22:19:24,141 - root - INFO - Processing batch 27/736
2025-04-23 22:19:33,252 - root - INFO - Processing batch 28/736
2025-04-23 22:19:43,520 - root - INFO - Processing batch 29/736
2025-04-23 22:19:53,819 - root - INFO - Processing batch 30/736
2025-04-23 22:20:02,127 - root - INFO - Processing batch 31/736
2025-04-23 22:20:07,842 - root - INFO - Processing batch 32/736
2025-04-23 22:20:13,419 - root - INFO - Processing batch 33/736
2025-04-23 22:20:22,948 - root - INFO - Processing batch 34/736
2025-04-23 22:22:21,235 - root - INFO - Processing batch 35/736
2025-04-23 22:22:26,470 - root - INFO - Processing batch 36/736
2025-04-23 22:22:32,893 - root - INFO - Processing batch 37/736
2025-04-23 22:22:38,871 - root - INFO - Processing batch 38/736
2025-04-23 22:22:49,506 - root - INFO - Processing batch 39/736
2025-04-23 22:22:56,771 - root - INFO - Processing batch 40/736
2025-04-23 22:23:04,550 - root - INFO - Processing batch 41/736
2025-04-23 22:23:12,283 - root - INFO - Processing batch 42/736
2025-04-23 22:23:22,851 - root - INFO - Processing batch 43/736
2025-04-23 22:23:29,537 - root - INFO - Processing batch 44/736
2025-04-23 22:23:39,737 - root - INFO - Processing batch 45/736
2025-04-23 22:23:48,947 - root - INFO - Processing batch 46/736
2025-04-23 22:23:55,175 - root - INFO - Processing batch 47/736
2025-04-23 22:24:00,875 - root - INFO - Processing batch 48/736
2025-04-23 22:24:08,202 - root - INFO - Processing batch 49/736
2025-04-23 22:24:12,631 - root - INFO - Processing batch 50/736
2025-04-23 22:24:21,162 - root - INFO - Processing batch 51/736
2025-04-23 22:24:29,011 - root - INFO - Processing batch 52/736
2025-04-23 22:24:34,691 - root - INFO - Processing batch 53/736
2025-04-23 22:24:39,394 - root - INFO - Processing batch 54/736
2025-04-23 22:24:47,783 - root - INFO - Processing batch 55/736
2025-04-23 22:24:55,849 - root - INFO - Processing batch 56/736
2025-04-23 22:25:05,608 - root - INFO - Processing batch 57/736
2025-04-23 22:25:13,961 - root - INFO - Processing batch 58/736
2025-04-23 22:25:24,297 - root - INFO - Processing batch 59/736
2025-04-23 22:25:33,582 - root - INFO - Processing batch 60/736
2025-04-23 22:25:40,489 - root - INFO - Processing batch 61/736
2025-04-23 22:25:45,739 - root - INFO - Processing batch 62/736
2025-04-23 22:25:52,670 - root - INFO - Processing batch 63/736
2025-04-23 22:25:58,756 - root - INFO - Processing batch 64/736
2025-04-23 22:26:04,613 - root - INFO - Processing batch 65/736
2025-04-23 22:26:11,722 - root - INFO - Processing batch 66/736
2025-04-23 22:26:17,745 - root - INFO - Processing batch 67/736
2025-04-23 22:26:24,760 - root - INFO - Processing batch 68/736
2025-04-23 22:26:37,348 - root - INFO - Processing batch 69/736
2025-04-23 22:26:43,499 - root - INFO - Processing batch 70/736
2025-04-23 22:26:49,115 - root - INFO - Processing batch 71/736
2025-04-23 22:26:54,112 - root - INFO - Processing batch 72/736
2025-04-23 22:27:02,359 - root - INFO - Processing batch 73/736
2025-04-23 22:27:10,507 - root - INFO - Processing batch 74/736
2025-04-23 22:27:16,378 - root - INFO - Processing batch 75/736
2025-04-23 22:27:22,458 - root - INFO - Processing batch 76/736
2025-04-23 22:27:30,244 - root - INFO - Processing batch 77/736
2025-04-23 22:27:38,865 - root - INFO - Processing batch 78/736
2025-04-23 22:27:45,299 - root - INFO - Processing batch 79/736
2025-04-23 22:27:54,327 - root - INFO - Processing batch 80/736
2025-04-23 22:28:01,844 - root - INFO - Processing batch 81/736
2025-04-23 22:28:10,013 - root - INFO - Processing batch 82/736
2025-04-23 22:28:16,524 - root - INFO - Processing batch 83/736
2025-04-23 22:28:25,749 - root - INFO - Processing batch 84/736
2025-04-23 22:28:33,123 - root - INFO - Processing batch 85/736
2025-04-23 22:28:44,929 - root - INFO - Processing batch 86/736
2025-04-23 22:28:45,029 - openai._base_client - INFO - Retrying request to /chat/completions in 0.496175 seconds
2025-04-23 22:29:00,798 - root - INFO - Processing batch 87/736
2025-04-23 22:29:10,192 - root - INFO - Processing batch 88/736
2025-04-23 22:29:18,593 - root - INFO - Processing batch 89/736
2025-04-23 22:29:24,558 - root - INFO - Processing batch 90/736
2025-04-23 22:29:30,886 - root - INFO - Processing batch 91/736
2025-04-23 22:29:41,180 - root - INFO - Processing batch 92/736
2025-04-23 22:29:46,866 - root - INFO - Processing batch 93/736
2025-04-23 22:29:59,040 - root - INFO - Processing batch 94/736
2025-04-23 22:30:06,062 - root - INFO - Processing batch 95/736
2025-04-23 22:30:13,028 - root - INFO - Processing batch 96/736
2025-04-23 22:30:21,004 - root - INFO - Processing batch 97/736
2025-04-23 22:30:28,245 - root - INFO - Processing batch 98/736
2025-04-23 22:30:33,810 - root - INFO - Processing batch 99/736
2025-04-23 22:30:40,203 - root - INFO - Processing batch 100/736
2025-04-23 22:30:52,329 - root - INFO - Processing batch 101/736
2025-04-23 22:31:05,555 - root - INFO - Processing batch 102/736
2025-04-23 22:31:12,992 - root - INFO - Processing batch 103/736
2025-04-23 22:31:18,081 - root - INFO - Processing batch 104/736
2025-04-23 22:31:28,324 - root - INFO - Processing batch 105/736
2025-04-23 22:31:34,893 - root - INFO - Processing batch 106/736
2025-04-23 22:31:41,451 - root - INFO - Processing batch 107/736
2025-04-23 22:31:52,812 - root - INFO - Processing batch 108/736
2025-04-23 22:31:59,737 - root - INFO - Processing batch 109/736
2025-04-23 22:32:09,165 - root - INFO - Processing batch 110/736
2025-04-23 22:32:16,222 - root - INFO - Processing batch 111/736
2025-04-23 22:32:22,407 - root - INFO - Processing batch 112/736
2025-04-23 22:32:29,640 - root - INFO - Processing batch 113/736
2025-04-23 22:32:40,288 - root - INFO - Processing batch 114/736
2025-04-23 22:32:51,825 - root - INFO - Processing batch 115/736
2025-04-23 22:33:03,260 - root - INFO - Processing batch 116/736
2025-04-23 22:33:14,144 - root - INFO - Processing batch 117/736
2025-04-23 22:33:23,072 - root - INFO - Processing batch 118/736
2025-04-23 22:33:29,113 - root - INFO - Processing batch 119/736
2025-04-23 22:33:41,636 - root - INFO - Processing batch 120/736
2025-04-23 22:33:51,088 - root - INFO - Processing batch 121/736
2025-04-23 22:33:59,305 - root - INFO - Processing batch 122/736
2025-04-23 22:34:08,091 - root - INFO - Processing batch 123/736
2025-04-23 22:34:17,094 - root - INFO - Processing batch 124/736
2025-04-23 22:34:24,268 - root - INFO - Processing batch 125/736
2025-04-23 22:34:37,302 - root - INFO - Processing batch 126/736
2025-04-23 22:34:44,473 - root - INFO - Processing batch 127/736
2025-04-23 22:34:50,760 - root - INFO - Processing batch 128/736
2025-04-23 22:34:58,992 - root - INFO - Processing batch 129/736
2025-04-23 22:35:05,601 - root - INFO - Processing batch 130/736
2025-04-23 22:35:11,426 - root - INFO - Processing batch 131/736
2025-04-23 22:35:20,282 - root - INFO - Processing batch 132/736
2025-04-23 22:35:27,141 - root - INFO - Processing batch 133/736
2025-04-23 22:35:40,435 - root - INFO - Processing batch 134/736
2025-04-23 22:35:49,955 - root - INFO - Processing batch 135/736
2025-04-23 22:36:03,810 - root - INFO - Processing batch 136/736
2025-04-23 22:36:14,797 - root - INFO - Processing batch 137/736
2025-04-23 22:36:27,971 - root - INFO - Processing batch 138/736
2025-04-23 22:36:34,299 - root - INFO - Processing batch 139/736
2025-04-23 22:36:40,800 - root - INFO - Processing batch 140/736
2025-04-23 22:36:47,930 - root - INFO - Processing batch 141/736
2025-04-23 22:37:00,247 - root - INFO - Processing batch 142/736
2025-04-23 22:37:12,819 - root - INFO - Processing batch 143/736
2025-04-23 22:37:21,439 - root - INFO - Processing batch 144/736
2025-04-23 22:37:28,826 - root - INFO - Processing batch 145/736
2025-04-23 22:37:37,462 - root - INFO - Processing batch 146/736
2025-04-23 22:37:46,608 - root - INFO - Processing batch 147/736
2025-04-23 22:37:54,572 - root - INFO - Processing batch 148/736
2025-04-23 22:38:06,814 - root - INFO - Processing batch 149/736
2025-04-23 22:38:20,261 - root - INFO - Processing batch 150/736
2025-04-23 22:38:27,568 - root - INFO - Processing batch 151/736
2025-04-23 22:38:37,706 - root - INFO - Processing batch 152/736
2025-04-23 22:38:45,181 - root - INFO - Processing batch 153/736
2025-04-23 22:38:54,708 - root - INFO - Processing batch 154/736
2025-04-23 22:39:02,179 - root - INFO - Processing batch 155/736
2025-04-23 22:39:10,865 - root - INFO - Processing batch 156/736
2025-04-23 22:39:25,120 - root - INFO - Processing batch 157/736
2025-04-23 22:39:33,051 - root - INFO - Processing batch 158/736
2025-04-23 22:39:43,349 - root - INFO - Processing batch 159/736
2025-04-23 22:39:51,306 - root - INFO - Processing batch 160/736
2025-04-23 22:39:59,107 - root - INFO - Processing batch 161/736
2025-04-23 22:40:06,049 - root - INFO - Processing batch 162/736
2025-04-23 22:40:13,128 - root - INFO - Processing batch 163/736
2025-04-23 22:40:21,304 - root - INFO - Processing batch 164/736
2025-04-23 22:40:29,237 - root - INFO - Processing batch 165/736
2025-04-23 22:40:39,864 - root - INFO - Processing batch 166/736
2025-04-23 22:40:47,182 - root - INFO - Processing batch 167/736
2025-04-23 22:40:54,183 - root - INFO - Processing batch 168/736
2025-04-23 22:41:00,343 - root - INFO - Processing batch 169/736
2025-04-23 22:41:15,207 - root - INFO - Processing batch 170/736
2025-04-23 22:41:22,329 - root - INFO - Processing batch 171/736
2025-04-23 22:41:29,263 - root - INFO - Processing batch 172/736
2025-04-23 22:41:38,552 - root - INFO - Processing batch 173/736
2025-04-23 22:41:46,709 - root - INFO - Processing batch 174/736
2025-04-23 22:41:54,802 - root - INFO - Processing batch 175/736
2025-04-23 22:42:03,058 - root - INFO - Processing batch 176/736
2025-04-23 22:42:08,920 - root - INFO - Processing batch 177/736
2025-04-23 22:42:15,241 - root - INFO - Processing batch 178/736
2025-04-23 22:42:23,815 - root - INFO - Processing batch 179/736
2025-04-23 22:42:31,858 - root - INFO - Processing batch 180/736
2025-04-23 22:42:39,794 - root - INFO - Processing batch 181/736
2025-04-23 22:42:47,464 - root - INFO - Processing batch 182/736
2025-04-23 22:42:56,071 - root - INFO - Processing batch 183/736
2025-04-23 22:43:03,428 - root - INFO - Processing batch 184/736
2025-04-23 22:48:56,142 - root - INFO - Processing batch 185/736
2025-04-23 22:49:03,455 - root - INFO - Processing batch 186/736
2025-04-23 22:49:11,432 - root - INFO - Processing batch 187/736
2025-04-23 22:49:17,586 - root - INFO - Processing batch 188/736
2025-04-23 22:49:35,162 - root - INFO - Processing batch 189/736
2025-04-23 22:49:44,798 - root - INFO - Processing batch 190/736
2025-04-23 22:49:57,828 - root - INFO - Processing batch 191/736
2025-04-23 22:50:03,991 - root - INFO - Processing batch 192/736
2025-04-23 22:50:11,960 - root - INFO - Processing batch 193/736
2025-04-23 22:50:22,266 - root - INFO - Processing batch 194/736
2025-04-23 22:50:32,547 - root - INFO - Processing batch 195/736
2025-04-23 22:50:41,343 - root - INFO - Processing batch 196/736
2025-04-23 22:50:47,504 - root - INFO - Processing batch 197/736
2025-04-23 22:50:55,815 - root - INFO - Processing batch 198/736
2025-04-23 22:51:02,069 - root - INFO - Processing batch 199/736
2025-04-23 22:51:07,570 - root - INFO - Processing batch 200/736
2025-04-23 22:51:13,408 - root - INFO - Processing batch 201/736
2025-04-23 22:51:21,110 - root - INFO - Processing batch 202/736
2025-04-23 22:51:31,061 - root - INFO - Processing batch 203/736
2025-04-23 22:51:37,672 - root - INFO - Processing batch 204/736
2025-04-23 22:51:46,629 - root - INFO - Processing batch 205/736
2025-04-23 22:51:55,915 - root - INFO - Processing batch 206/736
2025-04-23 22:52:05,861 - root - INFO - Processing batch 207/736
2025-04-23 22:52:21,896 - root - INFO - Processing batch 208/736
2025-04-23 22:52:37,341 - root - INFO - Processing batch 209/736
2025-04-23 22:52:45,165 - root - INFO - Processing batch 210/736
2025-04-23 22:52:53,549 - root - INFO - Processing batch 211/736
2025-04-23 22:53:01,765 - root - INFO - Processing batch 212/736
2025-04-23 22:53:17,045 - root - INFO - Processing batch 213/736
2025-04-23 22:53:23,849 - root - INFO - Processing batch 214/736
2025-04-23 22:53:32,972 - root - INFO - Processing batch 215/736
2025-04-23 22:53:43,741 - root - INFO - Processing batch 216/736
2025-04-23 22:53:55,827 - root - INFO - Processing batch 217/736
2025-04-23 22:54:07,561 - root - INFO - Processing batch 218/736
2025-04-23 22:54:17,945 - root - INFO - Processing batch 219/736
2025-04-23 22:54:28,316 - root - INFO - Processing batch 220/736
2025-04-23 22:54:35,361 - root - INFO - Processing batch 221/736
2025-04-23 22:54:41,463 - root - INFO - Processing batch 222/736
2025-04-23 22:54:55,415 - root - INFO - Processing batch 223/736
2025-04-23 22:55:01,827 - root - INFO - Processing batch 224/736
2025-04-23 22:55:08,532 - root - INFO - Processing batch 225/736
2025-04-23 22:55:15,605 - root - INFO - Processing batch 226/736
2025-04-23 22:55:25,286 - root - INFO - Processing batch 227/736
2025-04-23 22:55:36,777 - root - INFO - Processing batch 228/736
2025-04-23 22:55:44,711 - root - INFO - Processing batch 229/736
2025-04-23 22:55:53,164 - root - INFO - Processing batch 230/736
2025-04-23 22:56:00,637 - root - INFO - Processing batch 231/736
2025-04-23 22:56:05,431 - root - INFO - Processing batch 232/736
2025-04-23 22:56:13,742 - root - INFO - Processing batch 233/736
2025-04-23 22:56:23,057 - root - INFO - Processing batch 234/736
2025-04-23 22:56:30,232 - root - INFO - Processing batch 235/736
2025-04-23 22:56:39,947 - root - INFO - Processing batch 236/736
2025-04-23 22:56:48,204 - root - INFO - Processing batch 237/736
2025-04-23 22:56:58,479 - root - INFO - Processing batch 238/736
2025-04-23 22:57:07,358 - root - INFO - Processing batch 239/736
2025-04-23 22:57:23,661 - root - INFO - Processing batch 240/736
2025-04-23 22:57:32,761 - root - INFO - Processing batch 241/736
2025-04-23 22:57:39,423 - root - INFO - Processing batch 242/736
2025-04-23 22:57:50,172 - root - INFO - Processing batch 243/736
2025-04-23 22:57:57,787 - root - INFO - Processing batch 244/736
2025-04-23 22:58:04,394 - root - INFO - Processing batch 245/736
2025-04-23 22:58:14,510 - root - INFO - Processing batch 246/736
2025-04-23 22:58:21,168 - root - INFO - Processing batch 247/736
2025-04-23 22:58:28,881 - root - INFO - Processing batch 248/736
2025-04-23 22:58:37,643 - root - INFO - Processing batch 249/736
2025-04-23 22:58:54,199 - root - INFO - Processing batch 250/736
2025-04-23 22:59:01,485 - root - INFO - Processing batch 251/736
2025-04-23 22:59:10,339 - root - INFO - Processing batch 252/736
2025-04-23 22:59:20,857 - root - INFO - Processing batch 253/736
2025-04-23 22:59:30,723 - root - INFO - Processing batch 254/736
2025-04-23 22:59:37,328 - root - INFO - Processing batch 255/736
2025-04-23 22:59:43,585 - root - INFO - Processing batch 256/736
2025-04-23 22:59:52,217 - root - INFO - Processing batch 257/736
2025-04-23 23:00:00,428 - root - INFO - Processing batch 258/736
2025-04-23 23:00:09,273 - root - INFO - Processing batch 259/736
2025-04-23 23:00:15,439 - root - INFO - Processing batch 260/736
2025-04-23 23:00:27,592 - root - INFO - Processing batch 261/736
2025-04-23 23:00:36,510 - root - INFO - Processing batch 262/736
2025-04-23 23:00:45,128 - root - INFO - Processing batch 263/736
2025-04-23 23:00:56,273 - root - INFO - Processing batch 264/736
2025-04-23 23:01:03,797 - root - INFO - Processing batch 265/736
2025-04-23 23:01:11,276 - root - INFO - Processing batch 266/736
2025-04-23 23:01:17,843 - root - INFO - Processing batch 267/736
2025-04-23 23:01:28,840 - root - INFO - Processing batch 268/736
2025-04-23 23:01:35,198 - root - INFO - Processing batch 269/736
2025-04-23 23:01:41,839 - root - INFO - Processing batch 270/736
2025-04-23 23:01:49,318 - root - INFO - Processing batch 271/736
2025-04-23 23:01:59,146 - root - INFO - Processing batch 272/736
2025-04-23 23:02:07,847 - root - INFO - Processing batch 273/736
2025-04-23 23:02:13,892 - root - INFO - Processing batch 274/736
2025-04-23 23:02:22,060 - root - INFO - Processing batch 275/736
2025-04-23 23:02:30,031 - root - INFO - Processing batch 276/736
2025-04-23 23:02:37,112 - root - INFO - Processing batch 277/736
2025-04-23 23:02:44,987 - root - INFO - Processing batch 278/736
2025-04-23 23:02:56,810 - root - INFO - Processing batch 279/736
2025-04-23 23:03:04,742 - root - INFO - Processing batch 280/736
2025-04-23 23:03:15,070 - root - INFO - Processing batch 281/736
2025-04-23 23:03:24,998 - root - INFO - Processing batch 282/736
2025-04-23 23:03:33,361 - root - INFO - Processing batch 283/736
2025-04-23 23:03:40,729 - root - INFO - Processing batch 284/736
2025-04-23 23:03:52,038 - root - INFO - Processing batch 285/736
2025-04-23 23:04:04,536 - root - INFO - Processing batch 286/736
2025-04-23 23:04:14,247 - root - INFO - Processing batch 287/736
2025-04-23 23:04:25,301 - root - INFO - Processing batch 288/736
2025-04-23 23:04:32,535 - root - INFO - Processing batch 289/736
2025-04-23 23:04:39,563 - root - INFO - Processing batch 290/736
2025-04-23 23:04:46,264 - root - INFO - Processing batch 291/736
2025-04-23 23:04:52,596 - root - INFO - Processing batch 292/736
2025-04-23 23:05:00,281 - root - INFO - Processing batch 293/736
2025-04-23 23:05:09,651 - root - INFO - Processing batch 294/736
2025-04-23 23:05:18,835 - root - INFO - Processing batch 295/736
2025-04-23 23:05:26,831 - root - INFO - Processing batch 296/736
2025-04-23 23:05:33,643 - root - INFO - Processing batch 297/736
2025-04-23 23:05:42,667 - root - INFO - Processing batch 298/736
2025-04-23 23:05:52,162 - root - INFO - Processing batch 299/736
2025-04-23 23:06:02,254 - root - INFO - Processing batch 300/736
2025-04-23 23:06:13,333 - root - INFO - Processing batch 301/736
2025-04-23 23:06:17,194 - openai._base_client - INFO - Retrying request to /chat/completions in 0.449521 seconds
2025-04-23 23:06:22,032 - root - INFO - Processing batch 302/736
2025-04-23 23:06:29,978 - root - INFO - Processing batch 303/736
2025-04-23 23:06:37,056 - root - INFO - Processing batch 304/736
2025-04-23 23:06:44,686 - root - INFO - Processing batch 305/736

In [66]:
data_df.columns

Index(['id', 'doi', 'title', 'display_name', 'relevance_score',
       'publication_year', 'publication_date', 'ids', 'language',
       'primary_location', 'type', 'type_crossref', 'indexed_in',
       'open_access', 'authorships', 'institution_assertions',
       'countries_distinct_count', 'institutions_distinct_count',
       'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'fulltext_origin', 'cited_by_count',
       'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio',
       'is_retracted', 'is_paratext', 'primary_topic', 'topics', 'keywords',
       'concepts', 'mesh', 'locations_count', 'locations', 'best_oa_location',
       'sustainable_development_goals', 'grants', 'datasets', 'versions',
       'referenced_works_count', 'referenced_works', 'related_works',
       'abstract_inverted_index_v3', 'cited_by_api_url', 'counts_by_year',
       'updated_date', 'created_date', 'abstract', 'is_authors_truncated',
       'query', 'text'],
      dtype='object')

In [68]:
data_df.iloc[2]

id                                                 https://openalex.org/W2044379852
doi                                https://doi.org/10.1111/j.1467-789x.2004.00133.x
title                             Obesity in children and young people: a crisis...
display_name                      Obesity in children and young people: a crisis...
relevance_score                                                            4536.706
publication_year                                                               2004
publication_date                                                         2004-04-16
ids                               {'openalex': 'https://openalex.org/W2044379852...
language                                                                         en
primary_location                  {'is_oa': False, 'landing_page_url': 'https://...
type                                                                         review
type_crossref                                                       journal-article
indexed_in                                                   ['crossref', 'pubmed']
open_access                       {'is_oa': False, 'oa_status': 'closed', 'oa_ur...
authorships                       [{'author_position': 'first', 'author': {'id':...
institution_assertions                                                           []
countries_distinct_count                                                          1
institutions_distinct_count                                                       1
corresponding_author_ids                                                         []
corresponding_institution_ids                                                    []
apc_list                          {'value': 4940, 'currency': 'USD', 'value_usd'...
apc_paid                                                                        NaN
fwci                                                                         30.572
has_fulltext                                                                  False
fulltext_origin                                                                 NaN
cited_by_count                                                                 3799
citation_normalized_percentile    {'value': 0.998817, 'is_in_top_1_percent': Tru...
cited_by_percentile_year                                    {'min': 99, 'max': 100}
biblio                            {'volume': '5', 'issue': 's1', 'first_page': '...
is_retracted                                                                  False
is_paratext                                                                   False
primary_topic                     {'id': 'https://openalex.org/T10010', 'display...
topics                            [{'id': 'https://openalex.org/T10010', 'displa...
keywords                                                                         []
concepts                          [{'id': 'https://openalex.org/C511355011', 'wi...
mesh                              [{'descriptor_ui': 'D009765', 'descriptor_name...
locations_count                                                                   2
locations                         [{'is_oa': False, 'landing_page_url': 'https:/...
best_oa_location                                                                NaN
sustainable_development_goals     [{'display_name': 'Reduced inequalities', 'sco...
grants                                                                           []
datasets                                                                         []
versions                                                                         []
referenced_works_count                                                          482
referenced_works                  ['https://openalex.org/W1034691404', 'https://...
related_works                     ['https://openalex.org/W4382631096', 'https://...
abstract_inverted_index_v3                                                      NaN
cited_by_api_url                  https://api.openalex.org/works?filter=cites:W2...
counts_by_year                    [{'year': 2025, 'cited_by_count': 8}, {'year':...
updated_date                                             2025-04-18T06:09:52.956549
created_date                                                             2016-06-24
abstract                          Ten per cent of the world's school-aged childr...
is_authors_truncated                                                            NaN
query                             (child AND tool) OR (child AND instrument) OR ...
text                              Obesity in children and young people: a crisis...
Name: 5, dtype: object

In [94]:
cols = [
    'tool_name',
    'doi',
    'is_relevant',
    'is_relevant_reason',    
    'tool_type',            
    'age_range',
    'age_range_numerical',
    'child_outcomes',
    'child_outcomes_category',
    'parent_outcomes',
    'parent_outcomes_category',
    'population_validated',
    'measurement_format',
    'pros',
    'cons',    
    'geography',
    'country',  
    'author_countries', 
    'publication_year', 
    'cited_by_count',          
    'duration_minutes',
    'evidence',
    'global_vs_specific',
    'ease_of_use',
    'acceptability',
    'special_requirements',
    'cost',
    'id',
    'title',
    'text',
]

In [95]:
df_checked = (
    pd.read_json("afs_open_alex_scan_1.jsonl", lines=True)
    .merge(data_df[['id', 'publication_year', 'authorships', 'doi', 'title', 'text', 'is_retracted', 'cited_by_count']], on='id', how='left')
    .assign(
        author_countries = lambda df: df['authorships'].apply(extract_author_countries),
    )
    # convert lists to comma separated strings
    .assign(
        child_outcomes = lambda df: df['child_outcomes'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        child_outcomes_category = lambda df: df['child_outcomes_category'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        parent_outcomes = lambda df: df['parent_outcomes'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        parent_outcomes_category = lambda df: df['parent_outcomes_category'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        evidence = lambda df: df['evidence'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        pros = lambda df: df['pros'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        cons = lambda df: df['cons'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
        author_countries = lambda df: df['author_countries'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x),
    )
    .query("is_retracted == False")
)[cols]
df_checked

,tool_name,doi,is_relevant,is_relevant_reason,tool_type,age_range,age_range_numerical,child_outcomes,child_outcomes_category,parent_outcomes,...,duration_minutes,evidence,global_vs_specific,ease_of_use,acceptability,special_requirements,cost,id,title,text
0,Multiple developmental play assessments includ...,NaN,yes,The text lists multiple play-based assessment ...,Both,"infants, toddlers, preschoolers, young children",0-5,"cognitive development, temperament, social int...","Cognitive development, Social, emotional and b...","parent-child interaction, family interaction, ...",...,-1,These tools are used for assessing development...,both,"varies by tool, generally moderate due to obse...","Not explicitly described, but tools involve pa...",Some tools require trained administrators and ...,N/A,https://openalex.org/W1588659863,Play diagnosis and assessment,Play diagnosis and assessment DEVELOPMENTAL PL...
1,Children's Sleep Habits Questionnaire (CSHQ),https://doi.org/10.1093/sleep/23.8.1d,no,The tool assesses sleep habits in school-aged ...,Children,4-10 years,4-10,"sleep habits, sleep disorders",Physical health and development,,...,0,Adequate internal consistency and test-retest ...,specific,N/A,N/A,N/A,N/A,https://openalex.org/W2146721597,The Children's Sleep Habits Questionnaire (CSH...,The Children's Sleep Habits Questionnaire (CSH...
2,N/A,https://doi.org/10.1111/j.1467-789x.2004.00133.x,no,The text discusses childhood obesity and publi...,N/A,N/A,N/A,,,,...,0,,N/A,N/A,N/A,N/A,N/A,https://openalex.org/W2044379852,Obesity in children and young people: a crisis...,Obesity in children and young people: a crisis...
3,PedsQL™ 4.0 Generic Core Scales,https://doi.org/10.1097/00005650-200108000-00006,yes,The text describes the PedsQL 4.0 tool measuri...,Both,2 to 18 years,2-18,"physical health, emotional health, social heal...","Physical health and development, Mental health...",proxy-report of child's health-related quality...,...,20,Internal consistency reliability acceptable fo...,global,moderate,acceptable to children and parents as per study,N/A,N/A,https://openalex.org/W2323149989,PedsQL™ 4.0: Reliability and Validity of the P...,PedsQL™ 4.0: Reliability and Validity of the P...
4,N/A,https://doi.org/10.1136/bmj.320.7244.1240,no,The text describes BMI cutoffs for child overw...,N/A,N/A,N/A,,,,...,0,,N/A,N/A,N/A,N/A,N/A,https://openalex.org/W2104129218,Establishing a standard definition for child o...,Establishing a standard definition for child o...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7848,Eating in the Absence of Hunger (EAH) question...,https://doi.org/10.1002/eat.22213,no,The tool assesses eating behavior in overweigh...,Children,8-12 years,8-12,"eating behavior, caloric intake",Physical health and development,,...,0,Concurrent validity not supported for EAH ques...,specific,N/A,N/A,N/A,N/A,https://openalex.org/W1941325362,Concurrent and convergent validity of the eati...,Concurrent and convergent validity of the eati...
7849,N/A,https://doi.org/10.1176/appi.ajp.159.9.1541,no,"The tool predicts adolescent violence risk, no...",N/A,N/A,N/A,,,,...,13,Violence Proneness Scale score of 10+ at age 1...,specific,Moderate (13-item scale),N/A,Requires follow-up assessment at age 19,N/A,https://openalex.org/W2155444869,Predicting Adolescent Violence: Impact of Fami...,Predicting Adolescent Violence: Impact of Fami...
7850,Infant Behavior Questionnaire-Revised (IBQ-R),https://doi.org/10.4172/2161-1165.1000167,yes,The text describes the use of the Infant Behav...,Children,6 months old infants,0-1,"infant temperament, orienting and regulation, ...","Social, emotional and behavioral",,...,20,Higher maternal n3:n6 PUFA ratios attenuate ne...,both,moderate,N/A,Requires maternal completion when infant is 6 ...,N/A,https://openalex.org/W1845131196,Effects of prenatal social stress and maternal...,Effects of prenatal social stress and maternal...
7851,Emotional Availability Scales (EAS),https://doi.org/10.1002/imhj.20059,yes,The text describes the Emotional Availability ...,Both,6 weeks to 3 years 10 months,0-3,"emotional availability, behavioral disorders, ...","Social, emotional and behavioral",emotional availability,...,-1,Lower EAS ratings correlated with higher inten...,specific,moderate,N/A,Requires videotaping and trained raters for sc...,N/A,https://openalex.org/W2047885873,Emotional availability in infant psychiatry,Emotional availability in infant psychiatry In...
7852,N/A,https://doi.org/10.4324/9780203936825,no,The text is a table of contents for a book on ...,N/A,N/A,N/A,,,,...,0,,N/A,N/A,N/A,N/A,N/A,https://openalex.org/W1580778739,Modeling Contextual Effects in Longitudinal St...,Modeling Contextual Effects in Longitudinal St...

In [102]:
extra_fields = [
        {"name": "doi", "description": "The DOI of the publication."},
        {"name": "cited_by_count", "description": "The number of times the publication has been cited."},
        {"name": "text", "description": "The text of the publication."},
        {"name": "publication_year", "description": "The year of publication."},
        {"name": "id", "description": "The unique identifier of the publication."},
        {"name": "title", "description": "The title of the publication."},
    ]
all_fields = fields + extra_fields

# Create a table with explanations of all the fields used in the output table (cols columns)
df_explanations = pd.DataFrame.from_records(all_fields).drop(columns=['type'])
# Order it in the same order as the columns in the output table
df_explanations = df_explanations.set_index('name').reindex(cols).reset_index()
df_explanations

,name,description
0,tool_name,The name of the measurement or evaluation tool.
1,doi,The DOI of the publication.
2,is_relevant,One-word answer: 'yes' if the text is about a ...
3,is_relevant_reason,"Short explanation (one sentence, 20 words) of ..."
4,tool_type,Who is the tool used for - one of the followin...
5,age_range,"The age group the tool is suitable for, as des..."
6,age_range_numerical,Infer the probable age range in numerical form...
7,child_outcomes,List of child-related outcome domains the tool...
8,child_outcomes_category,Infer if the child-related outcomes are best c...
9,parent_outcomes,"List of parent-related outcomes, such as 'pare..."
10,parent_outcomes_category,Infer if the parent-related outcomes are best ...
11,population_validated,The population(s) or demographics the tool has...
12,measurement_format,"The format of the tool, e.g., 'questionnaire',..."
13,pros,"List of strengths or advantages of the tool, a..."
14,cons,"List of limitations, drawbacks, or reasons not..."
15,geography,"Geographic relevance or validation setting, if..."
16,country,"Infer country name or names based on the text,..."
17,author_countries,NaN
18,publication_year,The year of publication.
19,cited_by_count,The number of times the publication has been c...
20,duration_minutes,Approximate time in minutes it takes to comple...
21,evidence,Explanation of the tools effectiveness or evid...
22,global_vs_specific,'global' if the tool measures overall domains ...
23,ease_of_use,A qualitative description of the tool’s usabil...
24,acceptability,Acceptability to users (both those completing ...
25,special_requirements,"Any specific requirements, such as 'needs to b..."
26,cost,"Any cost-related information, such as 'free', ..."
27,id,The unique identifier of the publication.
28,title,The title of the publication.
29,text,The text of the publication.

In [104]:
from discovery_utils.utils import (
    google
)
sheet_id = "19BT2NlRcdH_uZG6dFMHtuNHX22WyfmfdpHJOsMkI-UI"

In [106]:
google.upload_data_to_gsheet(sheet_id, {"data": df_checked})
google.format_gsheet(sheet_id, "data", freeze_cols=2)

2025-04-24 10:37:34,958 - root - INFO - Connected to Google Sheet: Tools for measuring children and parents [April 2025]
2025-04-24 10:37:37,262 - root - INFO - Uploading DataFrame to sheet: data
/Users/karlis.kanders/Code/discovery_utils/.venv/lib/python3.12/site-packages/df2gspread/df2gspread.py:138: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str)
/Users/karlis.kanders/Code/discovery_utils/.venv/lib/python3.12/site-packages/df2gspread/df2gspread.py:138: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(str)
2025-04-24 10:39:54,364 - root - INFO - Upload completed successfully.
2025-04-24 10:39:57,519 - root - INFO - Connected to Google Sheet: Tools for measuring children and parents [24-04-2025]

In [ ]:
google.upload_data_to_gsheet(sheet_id, {"info": df_explanations})
google.format_gsheet(sheet_id, "info", freeze_cols=0)